(() => {
  const ids = new WeakMap(); let serial = 0;
  const id = o => { if (!o || !['object','function'].includes(typeof o)) return null; if (!ids.has(o)) ids.set(o,++serial); return ids.get(o); };
  const rows = [], attached = new WeakSet();
  const desc = e => !e ? null : e === window ? 'window' : e === document ? 'document' : `${e.tagName || e.nodeName}${e.id ? '#'+e.id : ''}${e.className && typeof e.className==='string' ? '.'+e.className.trim().replaceAll(' ','.') : ''}${e.dataset?.canvasNode ? '[data-canvas-node='+e.dataset.canvasNode+']' : ''}`;
  function fibers() { const el=document.getElementById('root'); if(!el)return []; const k=Object.keys(el).find(k=>k.startsWith('__reactContainer$')); if(!k)return []; const f=el[k], root=f.stateNode?.current||f, out=[], q=[root]; while(q.length){const x=q.pop();out.push(x);if(x.sibling)q.push(x.sibling);if(x.child)q.push(x.child)}return out; }
  const stores = () => [...new Set(fibers().map(f=>f.memoizedProps?.value).filter(v=>v&&typeof v.getSnapshot==='function'&&typeof v.select==='function'))];
  const state = s => { const v=s.getSnapshot();return {store:id(s),lifetime:id(v.lifetime),snapshot:id(v),revision:v.revision,workspaceId:v.workspaceId,projectId:v.projectId,surfaceId:v.surfaceId,selectedRefs:v.selectedRefs,primaryRef:v.primaryRef,selectedObjects:v.selectedObjects,supported:v.supported}; };
  const rect = e => e ? e.getBoundingClientRect().toJSON() : null;
  function geometry(pointerId=1) { const stage=document.querySelector('.ff-workspace-canvas'),viewport=document.querySelector('.ff-canvas-viewport');return {stage:rect(stage),border:stage&&{left:stage.clientLeft,top:stage.clientTop},captureHeld:stage?.hasPointerCapture(pointerId),viewport:rect(viewport),transform:viewport&&getComputedStyle(viewport).transform,nodes:[...document.querySelectorAll('[data-canvas-node]')].map(e=>({id:e.dataset.canvasNode,rect:rect(e),selected:e.getAttribute('aria-pressed')})),active:desc(document.activeElement),hasFocus:document.hasFocus(),width:innerWidth,height:innerHeight,dpr:devicePixelRatio}; }
  function gestures() { const out=[];for(const f of fibers()){let h=f.memoizedState,j=0;while(h&&typeof h==='object'&&j++<100){const v=h.memoizedState?.current;if(v&&typeof v==='object'&&v.capture&&'moved' in v&&'startScreen' in v)out.push({fiber:f.type?.name,kind:v.kind,pointerId:v.pointerId,moved:v.moved,union:v.union,owner:id(v.owner),lifetime:id(v.context.lifetime),revision:v.context.revision,startScreen:v.startScreen,origin:v.origin,bounds:v.outerBounds.toJSON(),camera:{x:v.canvas.viewportX,y:v.canvas.viewportY,zoom:v.canvas.zoom},capture:desc(v.capture)});h=h.next;}}return out; }
  function record(kind,data={}) { rows.push({kind,at:performance.now(),path:location.pathname,...data}); }
  function attach() { for(const s of stores())if(!attached.has(s)){attached.add(s);record('store-observed',{state:state(s)});s.subscribe(()=>record('store-notification',{state:state(s),activeCommittedStores:stores().map(id),stack:new Error('observational store notification').stack,geometry:geometry(),gestures:gestures()}));} }
  const events=['pointerdown','pointerup','pointermove','pointercancel','mousedown','mouseup','mousemove','click','focus','blur','focusin','focusout','gotpointercapture','lostpointercapture'];
  for(const type of events)for(const capture of [true,false])window.addEventListener(type,e=>{
    attach();record('event',{type:e.type,timeStamp:e.timeStamp,target:desc(e.target),currentTarget:desc(e.currentTarget),pathElements:e.composedPath().map(desc),clientX:e.clientX,clientY:e.clientY,button:e.button,buttons:e.buttons,altKey:e.altKey,ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,detail:e.detail,pointerId:e.pointerId,pointerType:e.pointerType,isPrimary:e.isPrimary,isTrusted:e.isTrusted,defaultPrevented:e.defaultPrevented,eventPhase:e.eventPhase,listenerCapture:capture,states:stores().map(state),geometry:geometry(e.pointerId),gestures:gestures()});
  },{capture,passive:true});
  new MutationObserver(()=>{attach();record('committed-dom-observation',{states:stores().map(state),geometry:geometry(),gestures:gestures()});}).observe(document,{subtree:true,childList:true,attributes:true});
  for(const type of ['resize','pagehide','pageshow'])window.addEventListener(type,e=>record(type,{persisted:e.persisted,states:stores().map(state)}),{passive:true});
  window.__diag={rows,id,desc,state,stores,geometry,gestures,record,attach};
})();
