import ast,sys,json,traceback
from pathlib import Path
R=Path(sys.argv[1]);ROOT=R.parents[1];sys.path.insert(0,str(R));t=ast.parse((R/'native_lifecycle.py').read_text());prefix=[]
for n in t.body:
 if isinstance(n,ast.Try):break
 prefix.append(n)
exec(compile(ast.Module(body=prefix,type_ignores=[]),str(R/'native_lifecycle.py'),'exec'))
b.raw('Page.addScriptToEvaluateOnNewDocument',{'source':(ROOT/'helpers/passive_d3.js').read_text()})
try:
 check('D3-before');b.reset();ready();b.click(P);b.wait('__lifecycleProbe.snapshot()[0].selectedRefs.length===1');stage=b.rect('.ff-workspace-canvas');x=stage['x']+8;y=stage['y']+8;b.mouse('mouseMoved',x,y);b.mouse('mousePressed',x,y);b.move(x+60,y+60);b.wait('!!document.querySelector("[data-canvas-marquee]")');pending=probe();assert pending['snapshot'][0]['selectedRefs'] and any(v['held'] for v in pending['capture']);
 b.raw('Debugger.enable',{});SOURCE=ROOT.parent/'FRONTEND_WAVE2_SLICE_1C_NODE_ORIGIN_CLICK_CORRECTION_AND_NATIVE_VALIDATION_V1';bundle=SOURCE/'build/assets/FoundationPages-BZ5M8zvA.js';js=bundle.read_text();pos=js.index('const d=()=>{c=!0,se.flushSync(()=>s.retireSelectionOwner("document"))}');start=pos+len('const d=()=>{');end=js.index('},p=()=>',start);column=lambda n:len(js[:n].encode('utf-16-le'))//2
 entry=b.raw('Debugger.setBreakpointByUrl',{'url':'http://127.0.0.1:4196/assets/'+bundle.name,'lineNumber':0,'columnNumber':column(start),'condition':"(__boundary.mark('product-handler-entry',null,s),false)"});assert len(entry['locations'])==1;sid=entry['locations'][0]['scriptId'];possible=b.raw('Debugger.getPossibleBreakpoints',{'start':{'scriptId':sid,'lineNumber':0,'columnNumber':column(start)},'end':{'scriptId':sid,'lineNumber':0,'columnNumber':column(end)+1},'restrictToFunction':True});returns=[v for v in possible['locations'] if v.get('type')=='return'];assert returns;loc=max(returns,key=lambda v:v['columnNumber']);assert loc['columnNumber']<=column(end);loc={k:v for k,v in loc.items() if k in ['scriptId','lineNumber','columnNumber']};finish=b.raw('Debugger.setBreakpoint',{'location':loc,'condition':"(__boundary.mark('product-handler-complete',null,s),false)"});(R/'DEBUGGER_PROBES.json').write_text(json.dumps({'entry':entry,'possible':possible,'completion':finish,'purpose':'direct handler entry/return; nonpausing conditions; D1 is debugger-free comparison','source_fragment':js[pos:end+1]},indent=2));armed=b.ev('__boundary.arm()');b.ev('__boundary.installLate()');
 b.raw('Page.navigate',{'url':'http://127.0.0.1:4196/lifecycle-away'});b.wait('document.title==="External lifecycle fixture"');away=probe();back();restored=probe();trace=b.ev('({documentId:__boundary.documentId,rows:__boundary.rows,snapshot:__boundary.snapshot()})');hide=[e for e in restored['events'] if e['event']=='pagehide'];actual=restored['id']==pending['id'] and any(e['persisted'] for e in restored['events'] if e['event']=='pageshow')
 (R/'D3_TRACE.json').write_text(json.dumps({'armed':armed,'pending':pending,'away':away,'restored':restored,'trace':trace,'actual_bfcache':actual},indent=2));assert actual,'actual BFCache prerequisite';ok=bool(hide) and all(not s['selectedRefs'] and s['primaryRef'] is None and s['lifetime']!=pending['snapshot'][0]['lifetime'] for e in hide for s in e['snapshot']);check('D3-after');record('real-pagehide-retires-before-suspension','historical unchanged assertion; expected diagnostic failure',hide,ok)
except Exception as x:
 (R/'FAILURE.json').write_text(json.dumps({'error':str(x),'traceback':traceback.format_exc(),'expected_original_assertion_failure':bool(b.checks and b.checks[-1]['test_identity']=='real-pagehide-retires-before-suspension')},indent=2));raise
finally:
 (R/'RESULTS.json').write_text(json.dumps({'kind':'DIAGNOSTIC_NOT_ACCEPTANCE','checks':b.checks},indent=2));(R/'COMMANDS.json').write_text(json.dumps(b.commands,indent=2));b.ws.close()
