import { describe, expect, it, vi } from 'vitest'
import { createInteractionStore, createProposal, applyProposal, type SurfaceAdapter } from './model'

const scope = { surfaceId: 'canvas' as const, workspaceId: 'w', projectId: 'p' }
function setup() {
  const store = createInteractionStore(scope)
  let objects = [{ id: 'note', kind: 'NODE' as const, title: 'Note', x: 0, y: 0 }, { id: 'other', kind: 'NODE' as const, title: 'Other' }]
  const handle = vi.fn<SurfaceAdapter['handle']>(action => {
    if (action.type === 'rename') objects = objects.map(o => o.id === action.targetId ? { ...o, title: action.title } : o)
    return true
  })
  store.register({ objects: () => objects, supports: ['rename', 'reveal'], handle })
  return { store, handle }
}
describe('product selection and intent boundary', () => {
  it('owns structural multiselection and rejects unknown presentation IDs', () => {
    const { store } = setup()
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note', 'other'], primaryId: 'other' })
    expect(store.getSnapshot().selectedObjects).toHaveLength(2)
    expect(store.getSnapshot().primarySelectedObject?.id).toBe('other')
    expect(store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['fake'] }).ok).toBe(false)
  })
  it('keeps an explicit primary while multi-selection can contract, and invalidates a proposal on time or selection', () => {
    const { store } = setup()
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note', 'other'], primaryId: 'other' })
    expect(store.getSnapshot().selectedObjects.map(object => object.id)).toEqual(['note', 'other'])
    expect(store.getSnapshot().primarySelectedObject?.id).toBe('other')
    const proposal = createProposal(store.getSnapshot(), '把这两段的音量都降低一点')
    expect(proposal.target).toContain('Note')
    expect(proposal.target).toContain('Other')
    expect(proposal.action).toBeNull()
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'], primaryId: 'note' })
    expect(store.getSnapshot().selectedObjects).toHaveLength(1)
    expect(applyProposal(store, proposal).ok).toBe(false)
    store.setTime({ unit: 'SIMULATED_STEP_0_20', playhead: 4 })
    const timeProposal = createProposal(store.getSnapshot(), 'inspect')
    store.setTime({ unit: 'SIMULATED_STEP_0_20', playhead: 5 })
    expect(applyProposal(store, timeProposal).ok).toBe(false)
  })
  it('lowers the same rename intent identically from every invocation source', () => {
    const { store, handle } = setup()
    for (const source of ['DIRECT', 'TOOLBAR', 'INSPECTOR', 'COMMAND', 'AGENT'] as const) {
      store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
      expect(store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'rename', targetId: 'note', title: source }, source).ok).toBe(true)
      expect(store.getSnapshot().primarySelectedObject?.title).toBe(source)
    }
    expect(handle).toHaveBeenCalledTimes(5)
  })
  it('rejects canonical requests before invoking any surface adapter', () => {
    const { store, handle } = setup()
    expect(store.dispatch({ category: 'CANONICAL_SEMANTIC', type: 'semantic', commandId: 'timeline.operation.apply' })).toMatchObject({ ok: false, reason: expect.stringContaining('server') })
    expect(handle).not.toHaveBeenCalled()
  })
  it('preserves selection while hiding inspector and resets in a fresh scope', () => {
    const { store } = setup()
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'inspect', open: false })
    expect(store.getSnapshot().primarySelectedObject?.id).toBe('note')
    expect(createInteractionStore({ ...scope, projectId: 'other' }).getSnapshot().selectedObjects).toEqual([])
  })
  it('interprets supplied local title and rejects stale proposals even after selection returns', () => {
    const { store } = setup()
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
    const proposal = createProposal(store.getSnapshot(), 'rename to Opening shot')
    expect(proposal.action).toMatchObject({ type: 'rename', title: 'Opening shot' })
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['other'] })
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
    expect(applyProposal(store, proposal).ok).toBe(false)
    const next = createProposal(store.getSnapshot(), 'rename to Closing shot')
    expect(applyProposal(store, next).ok).toBe(true)
    expect(store.getSnapshot().primarySelectedObject?.title).toBe('Closing shot')
  })
  it('fails closed for unknown interpretation, cross-store proposal and wrong categories', () => {
    const { store } = setup()
    expect(createProposal(store.getSnapshot(), 'make it amazing').action).toBeNull()
    const proposal = createProposal(store.getSnapshot(), 'inspect')
    expect(applyProposal(createInteractionStore(scope), proposal).ok).toBe(false)
    // Runtime callers cannot bypass the typed discriminant boundary.
    expect(store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'semantic', commandId: 'x' } as never).ok).toBe(false)
  })
  it('bounds explicit simulated time and projects revision questions without fabricating facts', () => {
    const { store } = setup()
    store.setTime({ unit: 'SIMULATED_STEP_0_20', playhead: 100, range: [4, 9] })
    expect(store.getSnapshot().time?.playhead).toBe(20)
    store.setRevisionPair({ from: 'r1', to: 'r2' })
    const proposal = createProposal(store.getSnapshot(), 'What changed between these revisions?')
    expect(proposal.action?.category).toBe('READ_ONLY_QUERY')
    expect(proposal.description).toContain('No diff facts')
  })
})

describe('scoped ordered selection invariants', () => {
  it('replaces in input order, toggles additions, removes primary, and clears with true no-ops', () => {
    const { store } = setup()
    const ref = (id: string) => ({ ...scope, kind: 'NODE' as const, localId: id })
    const select = (mode: 'replace' | 'toggle' | 'remove' | 'clear', ids: string[], primary?: string) => store.select({ mode, refs: ids.map(ref), primary: primary ? ref(primary) : undefined, lifetime: store.getSnapshot().lifetime, revision: store.getSnapshot().revision })
    expect(select('replace', ['other', 'note', 'other'], 'note').ok).toBe(true)
    expect(store.getSnapshot().selectedRefs.map(r => r.localId)).toEqual(['other', 'note'])
    expect(store.getSnapshot().primaryRef).toEqual(ref('note'))
    const before = store.getSnapshot()
    select('replace', ['other', 'note'], 'note')
    expect(store.getSnapshot()).toBe(before)
    select('toggle', ['other'])
    expect(store.getSnapshot().selectedRefs.map(r => r.localId)).toEqual(['note'])
    select('toggle', ['other', 'other'])
    expect(store.getSnapshot().selectedRefs.map(r => r.localId)).toEqual(['note', 'other'])
    expect(store.getSnapshot().primaryRef?.localId).toBe('other')
    select('remove', ['other'])
    expect(store.getSnapshot().primaryRef?.localId).toBe('note')
    select('clear', [])
    expect(store.getSnapshot()).toMatchObject({ selectedRefs: [], primaryRef: null, selectedObjects: [], primarySelectedObject: null })
    const empty = store.getSnapshot()
    select('clear', [])
    expect(store.getSnapshot()).toBe(empty)
    expect(empty.revision).toBe(before.revision + 4)
  })
  it('rejects wrong scope, kind, unknown, edge, stale revision and lifetime without changing membership', () => {
    const { store } = setup()
    const pin = store.getSnapshot()
    const ref = { ...scope, kind: 'NODE' as const, localId: 'note' }
    for (const bad of [{ ...ref, projectId: 'other' }, { ...ref, workspaceId: 'other' }, { ...ref, surfaceId: 'nle' }, { ...ref, kind: 'CLIP' }, { ...ref, kind: 'EDGE' }, { ...ref, localId: 'visual-guide' }]) {
      expect(store.select({ mode: 'replace', refs: [bad], lifetime: pin.lifetime, revision: pin.revision } as never).ok).toBe(false)
    }
    expect(store.select({ mode: 'replace', refs: [ref], primary: { ...ref, localId: 'other' }, lifetime: pin.lifetime, revision: pin.revision }).ok).toBe(false)
    expect(store.select({ mode: 'replace', refs: [ref], lifetime: {}, revision: pin.revision }).ok).toBe(false)
    expect(store.getSnapshot()).toBe(pin)
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
    expect(store.select({ mode: 'clear', refs: [], lifetime: pin.lifetime, revision: pin.revision }).ok).toBe(false)
  })
  it('reconciles changed projections and missing objects before Agent apply; leave rotates lifetime', () => {
    const store = createInteractionStore(scope)
    let objects = [{ id: 'note', kind: 'NODE' as const, title: 'Note', logicalRef: { kind: 'PROJECT' as const, entityId: 'p', referenceId: 'ref' } }, { id: 'other', kind: 'NODE' as const, title: 'Other' }]
    const handle = vi.fn(() => true)
    const leave = store.register({ objects: () => objects, supports: ['rename'], handle })
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note', 'other'] })
    const proposal = createProposal(store.getSnapshot(), 'rename to Later')
    expect(proposal.refs).toEqual(store.getSnapshot().selectedRefs)
    expect(proposal.logicalProjection).toEqual([{ presentation: store.getSnapshot().selectedRefs[0], logical: objects[0].logicalRef }])
    objects = objects.map(o => o.id === 'note' ? { ...o, logicalRef: { kind: 'PROJECT', entityId: 'new', referenceId: 'ref' } } : o)
    expect(applyProposal(store, proposal).ok).toBe(false)
    expect(handle).not.toHaveBeenCalled()
    expect(store.getSnapshot().revision).toBe(proposal.revision + 1)
    const refreshed = store.getSnapshot()
    store.reconcile()
    expect(store.getSnapshot()).toBe(refreshed)
    objects = objects.slice(1)
    store.reconcile()
    expect(store.getSnapshot().primaryRef?.localId).toBe('other')
    expect(store.getSnapshot().selectedRefs).toHaveLength(1)
    const beforeLeave = store.getSnapshot()
    leave()
    expect(store.getSnapshot().lifetime).not.toBe(beforeLeave.lifetime)
    expect(store.getSnapshot().primaryRef).toBeNull()
    expect(store.getSnapshot().revision).toBe(beforeLeave.revision + 1)
  })
  it('does not invalidate on inspector, Agent, reveal, or unchanged local geometry/title', () => {
    const { store } = setup()
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
    const revision = store.getSnapshot().revision
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'inspect', open: false })
    store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'agent', open: true })
    store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'reveal', targetId: 'note' })
    store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'rename', targetId: 'note', title: 'Note' })
    expect(store.getSnapshot().revision).toBe(revision)
  })
})

it('keeps published snapshots immutable and rejects a second active adapter', () => {
  const { store } = setup()
  expect(() => store.register({ objects: () => [], supports: [], handle: () => false })).toThrow('Only one active surface adapter')
  store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
  expect(Object.isFrozen(store.getSnapshot())).toBe(true)
  expect(Object.isFrozen(store.getSnapshot().selectedObjects)).toBe(true)
  expect(Object.isFrozen(store.getSnapshot().selectedObjects[0])).toBe(true)
  expect(Object.isFrozen(store.getSnapshot().selectedRefs[0])).toBe(true)
  store.setTime({ unit: 'SIMULATED_STEP_0_20', playhead: 4, range: [4, 9] })
  expect(Object.isFrozen(store.getSnapshot().time?.range)).toBe(true)
})

it('distinguishes presentation kinds sharing a local ID and rejects ambiguous ID-only operations', () => {
  const store = createInteractionStore(scope)
  const handle = vi.fn(() => true)
  store.register({ objects: () => [{ id: 'same', kind: 'NODE', title: 'Node' }, { id: 'same', kind: 'CLIP', title: 'Clip' }], supports: ['rename'], handle })
  const state = store.getSnapshot()
  expect(store.select({ mode: 'replace', refs: [{ ...scope, kind: 'NODE', localId: 'same' }, { ...scope, kind: 'CLIP', localId: 'same' }], lifetime: state.lifetime, revision: state.revision }).ok).toBe(true)
  expect(store.getSnapshot().selectedRefs).toHaveLength(2)
  expect(store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'rename', targetId: 'same', title: 'Ambiguous' }).ok).toBe(false)
  expect(handle).not.toHaveBeenCalled()
})


it('increments revision for a primary-only change and preserves ordered membership on a repeated no-op', () => {
  const { store, handle } = setup()
  store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note', 'other'], primaryId: 'note' })
  const before = store.getSnapshot()
  const proposal = createProposal(before, 'rename to Stale primary')
  expect(store.select({ mode: 'replace', refs: before.selectedRefs, primary: before.selectedRefs[1], lifetime: before.lifetime, revision: before.revision }).ok).toBe(true)
  const after = store.getSnapshot()
  expect(after.selectedRefs).toEqual(before.selectedRefs)
  expect(after.selectedObjects).toEqual(before.selectedObjects)
  expect(after.primaryRef?.localId).toBe('other')
  expect(after.primarySelectedObject?.id).toBe('other')
  expect(after.lifetime).toBe(before.lifetime)
  expect(after.revision).toBe(before.revision + 1)
  expect(applyProposal(store, proposal).ok).toBe(false)
  expect(handle).not.toHaveBeenCalled()
  expect(store.select({ mode: 'replace', refs: after.selectedRefs, primary: after.primaryRef!, lifetime: after.lifetime, revision: after.revision }).ok).toBe(true)
  expect(store.getSnapshot()).toBe(after)
})

it('Slice1C retirement invalidates ownership synchronously and rejects retained mutations and proposals', () => {
  const { store, handle } = setup()
  store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'select', ids: ['note'] })
  store.setRevisionPair({ from: 'a', to: 'b' })
  const before = store.getSnapshot()
  const proposal = createProposal(before, 'rename to Retired')
  const observer = vi.fn(() => expect(store.getSnapshot().selectedRefs).toEqual([]))
  store.subscribe(observer)
  store.retireSelectionOwner('document')
  expect(observer).toHaveBeenCalledOnce()
  const retired = store.getSnapshot()
  expect(retired).toMatchObject({ selectedRefs: [], primaryRef: null, selectedObjects: [], primarySelectedObject: null, supported: [], revisionPair: undefined, agentOpen: false })
  expect(retired.lifetime).not.toBe(before.lifetime)
  expect(retired.revision).toBe(before.revision + 1)
  expect(applyProposal(store, proposal).ok).toBe(false)
  expect(store.select({ mode: 'replace', refs: before.selectedRefs, lifetime: retired.lifetime, revision: retired.revision }).ok).toBe(false)
  expect(store.dispatch({ category: 'LOCAL_EPHEMERAL', type: 'agent', open: true }).ok).toBe(false)
  store.setTime({ unit: 'SIMULATED_STEP_0_20', playhead: 5 })
  store.setRevisionPair({ from: 'c', to: 'd' })
  store.retireSelectionOwner('owner')
  expect(store.getSnapshot()).toBe(retired)
  expect(handle).not.toHaveBeenCalled()
})

it('V5 dispatch enforces live history availability without selection and rejects canonical and other surfaces', () => {
  const store = createInteractionStore(scope)
  let available = true
  const handle = vi.fn(() => { available = false; return true })
  store.register({ objects: () => [], get supports() { return available ? ['undo-local'] : [] }, handle })
  expect(store.getSnapshot().selectedRefs).toEqual([])
  expect(store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'undo-local' }, 'COMMAND').ok).toBe(true)
  expect(store.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'undo-local' }, 'TOOLBAR').ok).toBe(false)
  expect(handle).toHaveBeenCalledTimes(1)
  available = true
  const revision = store.getSnapshot().revision
  expect(store.dispatch({ category: 'CANONICAL_SEMANTIC', type: 'semantic', commandId: 'undo-local' }).ok).toBe(false)
  expect(store.getSnapshot().revision).toBe(revision)
  expect(handle).toHaveBeenCalledTimes(1)
  for (const surfaceId of ['nle', 'review'] as const) {
    const other = createInteractionStore({ surfaceId })
    other.register({ objects: () => [], supports: ['undo-local', 'redo-local'], handle })
    expect(other.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'undo-local' }).ok).toBe(false)
    expect(other.dispatch({ category: 'WORKSPACE_PRESENTATION', type: 'redo-local' }).ok).toBe(false)
  }
  expect(handle).toHaveBeenCalledTimes(1)
})
