"""Offline reassessment and AST comparison only; historical programs are never executed."""
from pathlib import Path
import json,hashlib,ast,difflib,sys
from boundary_validator_v3 import verify
R=Path(__file__).resolve().parents[1];I=R/'inputs';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def get(p):return json.loads((I/p).read_text())
def put(p,d):(R/'results'/p).write_text(json.dumps(d,indent=2))
proof=get('runs/lifecycle-v2/DEPARTURE_BOUNDARY_PROOF.json');q=json.loads((R/'results/OFFLINE_QUALIFICATION_RESULTS.json').read_text());assert q['failed']==0
before=sha(I/'runs/lifecycle-v2/DEPARTURE_BOUNDARY_PROOF.json');v=verify(proof['trace'],proof['armed'],proof['actual_bfcache']);assert v['passed'];assert not proof['superseded_original_measurement_passed']
assessments=[]
for name in ['D1','D3']:
 path='runs/'+name+'/'+name+'_TRACE.json';d=get(path);result=verify(d['trace'],d['armed'],d['actual_bfcache']);assert result['passed'];rows=d['trace']['rows'];seq=lambda kind:[r['seq'] for r in rows if r['kind']==kind]
 assessments.append({'trace':name,'raw_sha256':sha(I/path),'offline_predicate_verdict':result,'admissibility':'PARTIAL_SUPPORT_ONLY_PREVIEW_EXCLUDED' if name=='D1' else 'RECORDED_DIAGNOSTIC_SUPPORT_WITH_PROBE_LIMITATIONS','preview_evidence':'EXCLUDED_INVALID_SELECTOR' if name=='D1' else 'RECORDED_NONEMPTY_PREVIEW_AND_CAPTURE_SUPPORT','direct_entry_return_proof':'NOT_ESTABLISHED','ordered_rows':{k:seq(k) for k in ['early-pagehide','early-microtask-pagehide','notify','late-pagehide','freeze','early-pageshow']},'limitation':'D1 preview field is structurally present but invalid-selector observation cannot establish preview absence. D3 unhit probes do not establish entry/return or non-execution. Neither is a new acceptance run.'})
oldp=I/'helpers/original_native_lifecycle.py';newp=I/'runs/lifecycle-v2/LIFECYCLE_V2_PROGRAM.py'
def assertions(p):
 return {n.args[0].value:ast.dump(n,include_attributes=False) for n in ast.walk(ast.parse(p.read_text())) if isinstance(n,ast.Call) and isinstance(n.func,ast.Name) and n.func.id=='record' and n.args and isinstance(n.args[0],ast.Constant)}
o,n=assertions(oldp),assertions(newp);assert o.keys()==n.keys();changed=[k for k in o if o[k]!=n[k]];affected='real-pagehide-retires-before-suspension';assert changed==[affected]
ledger=get('runs/lifecycle-v2/NATIVE_LIFECYCLE_RESULTS.json');checks=ledger['checks'];assert len(checks)==len({c['test_identity'] for c in checks})==12 and all(c['passed'] is True and c['result']=='PASS' for c in checks)
ident=get('INPUT_IDENTITIES.json');old_sha=sha(I/'helpers/boundary_validator.py');new_sha=sha(R/'helpers/boundary_validator_v3.py')
run={'evidence_commit':ident['prior_evidence_commit'],'prior_task':'FRONTEND_WAVE2_SLICE_1C_PAGEHIDE_OBSERVATION_BOUNDARY_DIAGNOSIS_AND_CONDITIONAL_HARNESS_CORRECTION_V1','run_directory':'runs/lifecycle-v2','documentId':proof['trace']['documentId'],'source_tree':ledger['tree'],'build_manifest':checks[0]['production_build_sha256'],'browser_version_recorded':checks[0]['browser_version'],'first_recorded_check_timestamp':checks[0]['timestamp'],'last_recorded_check_timestamp':checks[-1]['timestamp'],'proof_sha256':before,'raw_log_sha256':sha(I/'runs/lifecycle-v2/BROWSER_LIFECYCLE_RAW_LOG.txt'),'native_results_sha256':sha(I/'runs/lifecycle-v2/NATIVE_LIFECYCLE_RESULTS.json'),'program_sha256':sha(newp)}
put('ASSERTION_EVIDENCE_MAPPING.json',{'prior_run_identity':run,'old_validator_sha256':old_sha,'corrected_validator_sha256':new_sha,'affected_identity':affected,'unchanged_assertion_bodies':len(o)-len(changed),'programs_compared_by_AST_not_executed':True,'original_program_sha256':sha(oldp),'checks':[{'identity':c['test_identity'],'prior_result':c['result'],'historical_body_unchanged':o[c['test_identity']]==n[c['test_identity']],'current_action':'OFFLINE_VALIDATOR_REASSESSMENT' if c['test_identity']==affected else 'UNCHANGED_RECORDED_ASSERTION_BODY_ONLY_NOT_RERUN','prior_validator_verdict':proof['verdict'] if c['test_identity']==affected else None,'reassessed_verdict':v if c['test_identity']==affected else None,'prior_record_timestamp':c['timestamp']} for c in checks],'exclusions':['D1 preview invalid selector remains excluded','D3 direct conditional entry/return probes NOT_ESTABLISHED','old early sample failures retained','H4 and tracked-dist unresolved','No backend integration']})
put('OFFLINE_REASSESSMENT.json',{'outcome':'PASS_INTACT_RECORDED_DEPARTURE_PROOF','prior_run':run,'prior_verdict':proof['verdict'],'corrected_verdict':v,'old_validator_sha256':old_sha,'corrected_validator_sha256':new_sha,'diagnostic_reassessments':assessments,'fixture_reassessment':'15 historical decisions reconstructed/replayed in qualification ledger; recorded actual reload is identity reassessment, not new reload','qualification_controls':q['count'],'original_early_sample_failure':'RETAINED','fresh_browser_runs':0,'fresh_native_lifecycle_checks':0,'prior_native_lifecycle_result':'12_PASS_RECORDED_IN_PRIOR_TASK','earlier_49_of_50_ledger':'UNCHANGED_NOT_RELABELLED','new_evidence_collection_gap':'NONE_IN_INTACT_DEPARTURE_PROOF','cause':'OBSERVER_BOUNDARY_DEFECT_SUPPORTED_ON_RECORDED_CHROMIUM_PATH; external validator incompleteness corrected without product failure inference','boundary_limit':'Matched retirement and required cleanup before subsequent trusted freeze on recorded Chromium departure, not all-dispatch completion, general browser/crash/discard proof, or timer fallback'})
(R/'results/OLD_NEW_VALIDATOR.diff').write_text(''.join(difflib.unified_diff((I/'helpers/boundary_validator.py').read_text().splitlines(True),(R/'helpers/boundary_validator_v3.py').read_text().splitlines(True),fromfile='old/boundary_validator.py',tofile='new/boundary_validator_v3.py')))
print('OFFLINE_REASSESSMENT PASS; historical checks 12; unchanged bodies',len(o)-len(changed),'; fresh browsers 0; fresh native checks 0')
