from pathlib import Path
import json,sys,re,hashlib,collections
E=Path(__file__).parent;V=E/sys.argv[1];T=(V/'FINAL_TREE.txt').read_text().strip()
d=json.loads((V/'SOURCE_DELTA.json').read_text());a=json.loads((V/'TEST_IDENTITY_ACCOUNTING.json').read_text());b=json.loads((E/'FINAL_BROWSER_ACCOUNTING.json').read_text());build=json.loads((V/'BUILD_MANIFEST.json').read_text());target=json.loads((V/'TARGETED_FINAL.json').read_text());g=[json.loads((V/'gates'/f'{name}.json').read_text()) for name in json.loads((V/'FINAL_VALIDATION_PLAN.json').read_text())]
assert len(g)==7 and all(x['exit_code']==0 and x['implementation_tree']==T for x in g)
assert b['tree']==T and b['failed']==0 and b['checks']>0
product=[x['path'] for x in d['paths'] if x['path'].startswith('frontend/src/')];docs=[x['path'] for x in d['paths'] if x['path'] not in product]
assert len(product)+len(docs)==len(d['paths'])
counts=a['counts'];retained=counts['baseline']-counts['removed'];assert counts['baseline']-counts['removed']+counts['added']==counts['final']
assert set(x[0] for x in a['removed'])=={'frontend/src/product/render-browser/RenderBrowser.test.tsx','frontend/src/product/render-browser/source.test.ts'}
controls=(V/'gates/architecture-controls.log').read_text();control_counts={k:int(re.search(r'^# '+k+r' (\d+)$',controls,re.M)[1]) for k in ['tests','pass','fail','skipped']}
lint=(V/'gates/lint.log').read_text();m=re.search(r'(\d+) problems \((\d+) errors, (\d+) warnings\)',lint);lint_counts={'problems':int(m[1]),'errors':int(m[2]),'warnings':int(m[3])}
bs=hashlib.sha256((V/'BUILD_MANIFEST.json').read_bytes()).hexdigest()
fields={
'TASK':'FRONTEND_WAVE2_RENDER_OBSERVABILITY_V7','LANE':'FRONTEND','FRONTEND_BRANCH':'refs/heads/agent/frontend-wave2-product-ux-v1',
'PRIOR_V6_REVIEW_ADOPTION_RECORDED':'YES — existing frontend/governance/UX_WAVE_1_REVIEW.md append; Owner adoption of fixed-evidence static read-only frontend review; prior evidence commit 7362b5e9e2e6df680b03a9666d5b8db264d9e413, manifest 08ff3f82a0b607e28e98b24acf1db0eb1d868bd304fef784a63a9b34157e0e33; not real contract/permission/integration acceptance',
'SELECTED_FEATURE':'Render observability only; STOP before Workflow UX',
'PLAN_SOURCE_AND_ITEM':'docs/architecture/governance/frontend-product-information-architecture-v1.md — adopted priority Scene/Shot > Render observability > Workflow UX > bounded NLE editing > Agent-assisted creative; existing /operations/renders increment',
'BASELINE_IMPLEMENTATION_TREE':d['baseline_tree'],'FINAL_IMPLEMENTATION_TREE':T,'PRODUCT_CHANGED_PATHS':product,'DOCUMENTATION_CHANGED_PATHS':docs,
'REUSED_RENDER_SURFACES_AND_CONTRACTS':'Existing /operations/renders -> RenderBrowser; existing provider, EffectiveAccess, shared Selection owner, InteractionDialog, horizontal shell/design/localization. Inspected RenderJobSummary, render-jobs API, legacy result list/detail; richer observability does not exist in the five-field agreed type. No parallel center/registry/permission or legacy transport invocation.',
'RENDER_CONSUMPTION_CONTRACT_STATUS':'FRONTEND UNAGREED consumer proposal; no agreed HTTP endpoint, server permission key or canonical DTO claimed. Real read requires host-supplied matching HOST_AGREED binding and SERVER EffectiveAccess; generic visibility, proposal and test-only keys rejected.',
'USER_VISIBLE_OUTCOME':'Bounded supplied Render ID/name discovery, source-supported status filter, stable name/ID sort, reachable reset, manual refresh/query retry/loading cancel, readonly task detail, return preserving filters and launcher focus. EN/zh-CN; unconfigured ordinary route unavailable.',
'PROGRESS_AND_STATUS_SEMANTICS':'Unknown source statuses literal/neutral. Source value/unit/total/totalUnit/stage retained, including invalid finite values. Percent only finite consistent units, positive total, 0<=value<=total; never clamp or synthesize ETA/status/time. Source times literal; frontend successful-fetch time separately labelled.',
'FAILURE_AND_ATTEMPT_BOUNDARIES':'Validated supplied user-safe summary/code/time only; React text, strict shape and bounded disclosure checks. Explicit attempt identities/ordinals/task/parent/retry links only; no generated history. Task status and attempt status separate; missing/empty/bounded/complete distinct.',
'ARTIFACT_ACCESS_BOUNDARIES':'Supplied readonly safe ID/name/type/literal availability/version/explicit task link. Missing/empty/bounded/denied/unavailable/unknown/stale/inspectable metadata distinct. Metadata/task visibility grants no Artifact read. No verified typed destination/independent access receipt, therefore no open/download/URL action.',
'PERMISSION_AND_ACTION_BOUNDARIES':'EffectiveAccess authoritative projection; no visibility/role/testkey/client-flag authorization. Query retry is not render retry. No submit, execution cancel, rerender, task retry, artifact delete/publish, workflow/timeline/canonical mutation, provider/worker/billing/quota calls.',
'CONTEXT_AND_STALE_RESULT_HANDLING':'principal/tenant/session/Project, complete access projection, binding, adapter and Selection owner lifetime key the session; replacement/unmount/retirement aborts reads and clears data/dialog. Generation fences late success/rejection. StrictMode registration and ready/pending retirement tested. Explicit stale failure clears data; stale successful source snapshot is labelled stale, not called fresh.',
'MOCK_AND_REAL_DATA_BOUNDARIES':'Ordinary application has no implicit fixture URL switch, default account or real query. Separate loopback opt-in host wraps exact registered route tree with simulated identity/access and controlled adapter. Dashboard fixture reads and inert disposable auth marker are harness-only. No real integration.',
'TARGETED_TEST_RESULTS':{'passed':target['numPassedTests'],'total':target['numTotalTests'],'failed':target['numFailedTests'],'pending':target['numPendingTests'],'report':'validation/TARGETED_FINAL.json'},
'FULL_TEST_IDENTITY_ACCOUNTING':{**counts,'retained_baseline_identities':retained,'report':'validation/TEST_IDENTITY_ACCOUNTING.json','interpretation':'49 replaced identities are confined to the two rewritten Render suites; unknown-status rejection, hardcoded proposal binding and product URL fixture expectations intentionally superseded. Consolidated schema cases reduce expanded identity count. Not a claim that all 797 old identities remain. All unrelated identities retained.'},
'REQUIRED_FRONTEND_GATE_RESULTS':{'required':len(g),'passed':sum(x['exit_code']==0 for x in g),'architecture_controls':control_counts,'lint':lint_counts,'commands':'validation/FINAL_VALIDATION_PLAN.json','raw':'validation/gates/'},
'FOCUSED_BROWSER_RESULTS':{'checks':b['checks'],'passed':b['passed'],'failed':b['failed'],'screenshots':b['screenshots'],'served_files':b['served_files'],'served_hash_differences':b['served_hash_differences'],'browser':'Chromium CDP headless; focus emulation; desktop 1440x1000 and narrow 390x844 EN/zh-CN','assistance':'DOM locale/locator/scrollIntoView and explicit source-mode/delay controls disclosed','native_exits':b['teardown'],'not_certified':'physical device/touch/virtual keyboard/OS IME/screenreader; width pass not mobile certification'},
'BUILD_MANIFEST_SHA256':bs,'BACKEND_REQUIREMENTS_UPDATED':'YES — existing FB-GAP-005 in both requested records; future bounded pinned frontend/backend controlled-Project readonly authorized/denied/error/stale and zero-write acceptance described, not performed',
'NEW_BACKEND_REQUIREMENTS':'No new requirement IDs; richer UNAGREED FB-GAP-005 consumption details only. No full-platform prerequisite.',
'BACKEND_CHANGES':'0 task-authorized backend source changes; no backend lane audit or stationarity requirement',
'TRACKED_DIST_CHANGES':'0; named frontend/dist 8 files byte/mode/membership preserved, fresh runtime built externally',
'BACKEND_STATIC_CHANGES':'0 generating-command changes; configured backend static destination 3 files byte/mode/membership verified before/after final gates/browser; product mounts read-only',
'REAL_INTEGRATION_PERFORMED':'NO',
'BOUNDED_PRESERVATION_RESULT':'PASS — final 1005 scoped paths match exact tree bytes/modes/membership; 990 baseline paths outside allowlist unchanged; real index/HEAD/branch preserved. Previous V6 public package/receipt/archive hashes preserved. No whole-repo/parallel-backend/whole-host stationarity claim.',
'H4_RECONCILIATION_STATUS':'UNCHANGED / unresolved historical dispositions retained; guards not changed, no debt-closure claim',
'FORMAL_SLICE1C_LEDGER_STATUS':'UNCHANGED / separate authority and review; no closure or release claim',
'PRODUCT_COMMIT_FREEZE_MERGE_PUSH':'NOT_PERFORMED; original HEAD f5e19cf53fd010eea2935dd29557e82a879e042c retained; no real-index staging',
'PRODUCT_PUBLICATION':'NOT_PERFORMED',
'EVIDENCE_DELIVERY_STATUS':'LOCAL_SANITIZED_REVIEW_PACKAGE; local manifest/archive verification recorded in detached LOCAL_PACKAGE_VERIFICATION.json; parent independently verifies and separately publishes',
'EVIDENCE_COMMIT_SHA':'NOT_ESTABLISHED — child did not publish','REVIEW_INDEX_URL':'NOT_ESTABLISHED — LOCAL_REVIEW_PACKAGE/REVIEW_INDEX.md only','RAW_REVIEW_INDEX_URL':'NOT_ESTABLISHED — no remote publication','MACHINE_INDEX_URL':'NOT_ESTABLISHED — LOCAL_REVIEW_PACKAGE/REVIEW_INDEX.json only','PUBLIC_MANIFEST_SHA256':'NOT_ESTABLISHED — public publication not performed; local manifest hash belongs in detached receipt, not a self-referential report','REMOTE_VERIFICATION':'NOT_PERFORMED by child','INDEPENDENT_REVIEW':'REQUIRED — no implementation acceptance claimed','STOP':'BEFORE_WORKFLOW_UX; parent independent review and separately authorized evidence-only publication only'}
(E/'FINAL_FIELDS.json').write_text(json.dumps(fields,ensure_ascii=False,indent=2)+'\n')
lines=['# V7 渲染可观测性：本地独立评审包','',f'**状态：已实现并完成限定工程验证；独立评审 REQUIRED。** 基线 `{d["baseline_tree"]}` → 未冻结实现树 `{T}`。禁止产品提交、冻结、合并或发布；此包尚未远程发布。','','## 交付与验证','',f'- 原有 Render 表面扩展；{len(product)} 个产品/测试/本地化路径及 {len(docs)} 个治理文档路径，共 {len(d["paths"])} 个变化路径。新增一个样式文件，已在两个当前分类账中登记。',f'- 七项最终树门禁全部 exit 0；定向 {target["numPassedTests"]}/{target["numTotalTests"]}，完整前端 {counts["passed"]}/{counts["final"]}，架构控制 {control_counts["pass"]}/{control_counts["tests"]}。Lint {lint_counts["errors"]} 错误、{lint_counts["warnings"]} 警告。',f'- 完整测试身份：原始 797；保留 {retained}，替换删除 {counts["removed"]}，新增 {counts["added"]}，最终 {counts["final"]}；失败/跳过/重复均为 0。不得表述为“原 797 个测试全部不变”。所有身份及原始 reporter 均保留。',f'- 最终浏览器 {b["passed"]}/{b["checks"]} 检查，{b["screenshots"]} 张截图；{b["served_files"]} 个发射文件逐字节 HTTP 哈希吻合。Chromium 与检查脚本自然 exit 0；fixture 服务按预期 SIGTERM -15，端口无残留。',f'- 外部构建共 {len(build["files"])} 个文件，含真实应用与独立 fixture 入口及两个 HTML；不是继承 V6 的 14 文件计数。必需资源无缺失；两个 HTML 均引用同一个历史缺失可选 `/vite.svg`，没有把其 404 当作应用资源 PASS。','','## 真实/模拟、权限与行为边界','','普通应用未配置时仅显示不可用；真实服务器契约、授权和集成均未建立。单独 loopback fixture host 只用于显式模拟验证，未在产品增加 URL fixture 开关。源状态、时间、失败、尝试和制品字段均作为只读投影；未知状态不推断成功/失败，任务可见性不授予制品读取。有效进度仅按已验证同单位数值计算，140/100 等有限无效值保留原值但不钳制、不给百分比。查询重试不等于任务重试。','','## 本次发现、纠正与保留记录','','首次 PTY `codex-router` 因 PATH command-not-found 退出 127；原日志保留，随后使用已发现的绝对路径启动，不是工具权限绕过。主 writer 与修正 writer 均 exit 0。主 writer 的预期 TDD RED、类型错误及中间失败保留；第二 writer 用三个失败回归证明了测试专用键重新标记与缺失原始进度字段问题，再完成修正及非空生命周期断言。最终七门禁只有一个精确树版本，全部成功。','','writer 报告观察到 external `package_local.py` 并发改变：这是 controller 在 writer 运行期间补充本地打包字段及生成目标保全记录的已知改动（本会话 patch receipts），不是产品漂移、writer 越界或对不明漂移的吸收。其原始观察记录保留。初始 writer 的 shell-expanded lint 警告数 13 不具完整递归范围；最终实际递归 lint 为 46 警告/0 错误，前者不转用。','','第一次浏览器执行 43 检查/27 截图通过，保留为先前成功执行。随后在同一只读构建上加入制品/失败尝试/窄屏制品下部可见性检查并完整重跑；最终口径为 46/30，而不是相加 89。','','## 视觉与验证限制','','已逐张审看代表性最终截图：桌面列表、身份详情、下部制品与失败尝试、中文窄屏列表及下部详情。窄屏信息和长字面值换行，发现控件、源披露与收据占据较多首屏；完整任务/详情需要垂直及内部滚动。深滚动时共享对话框标题/关闭按钮不持续显示，Escape 关闭和返回启动器焦点已验证。DOM scrollIntoView 是披露的辅助，不是物理触摸滚动认证。文档宽度通过不代表首屏全部可见或完整移动端可用性验收。','','未执行物理设备、触控、虚拟键盘、OS IME、屏幕阅读器或真实后端/权限/跨进程集成。源码中的 pagehide/pageshow 生命周期是模拟组件事件证据，不是新做的真实 bfcache 生命周期资格验证。H4、正式 Slice1C 与发布仍单列，不宣称治理欠账清零。','','## 原始证据与离线复核入口','','- `validation/TASK_DELTA.patch`：完整 binary/full-index 补丁；`PATCH_REPLAY.json` 证明外部索引重放得到同一最终树。','- `validation/source/` 与 `validation/before-source/`：所有改变路径最终/基线完整字节；`context/`：完整前端源码、测试、类型、守卫、依赖配置及实际决策文档。','- `validation/gates/`：每门精确命令、containment、native exit、原始输出；`FULL_UNIT.json`/`TARGETED_FINAL.json` 与原始 `V6_FULL_UNIT.json` 可复算身份。','- `browser/`：最终原生指令、断言、HTTP/服务字节哈希、截图、辅助和退出记录；`prior-browser-attempts/` 保留前次成功执行。','- `validation/build/`：完整构建文件；大 JS 保留原始字节并提供有序 UTF-8 review chunks 与重建表。','- `MANIFEST.sha256` 排除自身；`REVIEW_INDEX.json` 不包含自身/后生成 manifest；archive/hash 在外部 detached receipt 中，避免自哈希循环。','','## 必需交付字段','']
for k,v in fields.items():lines += [f'### {k}','',('```json\n'+json.dumps(v,ensure_ascii=False,indent=2)+'\n```') if isinstance(v,(dict,list)) else str(v),'']
(E/'FINAL_REVIEW_REPORT_ZH.md').write_text('\n'.join(lines)+'\n')
# Link executed structured test identities to their actual implementation predicates.
groups=[('source.ts:parseRenderSnapshot/validateRelationships/progressSchema/deriveProgressPercent','frontend/src/product/render-browser/source.test.ts'),('source.ts:sourceDisposition/hasExpectedProjection/renderScopeIsValid/contextKey; fixture.ts:createRendersFixture','frontend/src/product/render-browser/source.test.ts'),('RenderBrowser.tsx:RenderBrowser/RenderBrowserSession/load/cancel; Selection owner integration','frontend/src/product/render-browser/RenderBrowser.test.tsx'),('RenderBrowser.tsx:RenderDetail/ArtifactDetail/FailureDetail; shared InteractionDialog, localization','frontend/src/product/render-browser/RenderBrowser.test.tsx'),('app/routeTree.tsx:existing operations/renders registration; AppShell and interaction/localization regression suites','frontend/src/app/routeTree.test.tsx')]
ml=['# Source → executed test / browser map','',f'Exact implementation `{T}`. Raw expanded identities in validation/TEST_IDENTITY_ACCOUNTING.json. This map is not a claim of exhaustive input-space proof.','']
for symbol,file in groups:
 ml += ['## '+symbol,'','Executed identities in `'+file+'`:','']
 ml += ['- `'+json.dumps(x['identity'],ensure_ascii=False)+'` — '+x['status'] for x in a['executed'] if x['identity'][0]==file]
 ml+=['']
ml += ['## Guard mechanisms and blind spots','','Unchanged frontend-architecture-guard inventories governed source paths against both current ledger inputs and checks forbidden authority/import/mutation patterns. Unchanged Node controls execute positive and negative cases; 120/120 passed. This is static structural enforcement, not backend authorization/integration proof. Typecheck and lint are separate from executed Vitest behavior; browser uses built output rather than test DOM.','', '## Predecessor identity disposition','',f'{retained} baseline identities retained exactly; 49 removed and 41 new, all confined to the two Render suites. The full before/after test files are exported as source endpoints. Old five-field/ID-profile-only filter, unknown-status rejection, fixed proposed real binding, and URL fixture expectations are intentionally superseded by this authorized feature. Old expanded schema-negative cases are consolidated into bounded behavior loops; the exact old parameterized instance set was not executed unchanged on V7. No skip or fixed total was added.','', 'The final native assertions, expressions, their passing values and timestamps are in browser/NATIVE_CHECKS.json. Native pointer/key activation is distinct from DOM locale/locator/scroll assistance and explicit fixture outcome injection, all in browser/ASSISTANCE.json.','']
(E/'SOURCE_CONTRACT_TEST_MAPPING.md').write_text('\n'.join(ml))
(E/'CONTROLLER_REVIEW.md').write_text('# Controller review — independent review still REQUIRED\n\n'+f'Exact tree `{T}` verified after both codex-router writers exited and no worktree writer descendants remained. Accepted V6 tree recovery, code/contracts/EffectiveAccess/Selection/dialog review, four bounded correction observations, final seven contained gates, full identity accounting, patch replay, emitted+served build hashes, final browser and representative screenshot review completed.\n\n'+f'Counts: {len(d["paths"])} paths ({len(product)} product/test/localization + {len(docs)} governance); full {counts["passed"]}/{counts["final"]}; targeted {target["numPassedTests"]}/{target["numTotalTests"]}; controls {control_counts["pass"]}/{control_counts["tests"]}; browser {b["passed"]}/{b["checks"]}, {b["screenshots"]} screenshots; build {len(build["files"])} files.\n\n'+'Correction observations are preserved separately with RED and GREEN receipts. External package helper edits detected by the correction writer were controller-owned documented tool edits, not product drift. Existing source outside the 15-path allowlist, real index/HEAD/branch, historical V6 seal and named generated-output targets remained unchanged. No guards/H4/Skill bodies/backend lane changes, remote publication or real integration.\n\n'+'Known limits: narrow layout requires vertical/internal scrolling and long source-value wrapping; deeply scrolled dialog header/close not persistent, native Escape/focus return proven. DOM scroll/locale assistance and CDP focus emulation disclosed. All 797 predecessor test identities were not preserved: 49 changed Render identities replaced by 41, producing 789; no outside Render-suite identities removed. Static guards are not semantic/server permission proof. Final lint is 46 warnings/0 errors; prior shell-expanded 13-warning writer invocation not equivalent.\n\n'+'Parent must independently inspect this complete local package before separately authorized evidence-only publication. STOP before Workflow and all product commit/freeze/merge/push/publication.\n')
print(json.dumps({'tree':T,'product_paths':len(product),'documentation_paths':len(docs),'retained_tests':retained,'report_fields':len(fields),'report':'FINAL_REVIEW_REPORT_ZH.md'},indent=2))
