import { createCatalog, messageAt, type CatalogNamespaces, type LocalizationCatalog, type MessageDefinition, type SupportedLocale, type ValidationResult } from './catalog'
import sourceManifest from './source-manifest.json'

const message = (value: string, params: readonly string[] = []): MessageDefinition => ({ message: value, params })

const englishNamespaces: CatalogNamespaces = {
  common: {
    greeting: message('Hello, {name}', ['name']),
    untitled: message('Untitled'),
    none: message('None'),
    localeSelector: message('Product UI language'),
    localeEnglish: message('English'),
    localeChinese: message('简体中文'),
  },
  shell: {
    'notifications.title': message("Notifications"),
    'notifications.close': message("Close notifications"),
    'notifications.entryUnknown': message("Notifications · unread count unknown"),
    'notifications.entryCount': message("Notifications · {count} unread in inbox", ["count"]),
    'notifications.simulatedBadge': message("SIMULATED"),
    'notifications.simulated': message("SIMULATED · In-memory examples only. No real account, notification or permission is connected."),
    'notifications.real': message("Connected inbox source. Destination access is checked separately."),
    'notifications.originUnavailable': message("Inbox connection unavailable."),
    'notifications.unavailable': message("Notifications are not connected yet. Unread count is unknown."),
    'notifications.filter': message("Filter notifications"),
    'notifications.all': message("All"),
    'notifications.unread': message("Unread"),
    'notifications.read': message("Read"),
    'notifications.refresh': message("Refresh notifications"),
    'notifications.readAll': message("Mark entire inbox as read"),
    'notifications.readAllScope': message("Applies to the entire inbox, including notifications outside this snapshot and filter."),
    'notifications.readAllUnsupported': message("Marking the entire inbox read is not supported by this source."),
    'notifications.singleUnsupported': message("Marking individual notifications read is not supported by this source."),
    'notifications.loading': message("Loading notifications…"),
    'notifications.loaded': message("Notification snapshot loaded."),
    'notifications.empty': message("No notifications in this snapshot."),
    'notifications.denied': message("Inbox access was denied."),
    'notifications.error': message("Notifications could not be loaded. Refresh to try again."),
    'notifications.notFound': message("This notification is no longer available. Refresh to check the inbox."),
    'notifications.marking': message("Waiting for read confirmation…"),
    'notifications.readError': message("The notification could not be confirmed as read. Refresh before trying again."),
    'notifications.readConfirmed': message("Read confirmed. The inbox has been requested again."),
    'notifications.partialRead': message("Some notifications could not be marked read. The inbox has been requested again."),
    'notifications.globalCount': message("{count} unread in the entire inbox.", ["count"]),
    'notifications.unknownCount': message("Unread count is unknown. Loaded items are not the inbox total."),
    'notifications.limited': message("Showing a limited snapshot. More notifications may exist."),
    'notifications.complete': message("All notifications matching this filter were returned in this snapshot."),
    'notifications.list': message("Notification list"),
    'notifications.untitled': message("Untitled notification"),
    'notifications.readDetail': message("Read notification: {title}", ["title"]),
    'notifications.markRead': message("Mark as read"),
    'notifications.detail': message("Notification detail"),
    'notifications.openResource': message("Open related resource"),
    'notifications.simulatedTarget': message("Opens the simulated project overview. No real account or resource permission is granted."),
    'notifications.destinationChecks': message("The destination checks current resource access. This notification does not grant permission."),
    'notifications.unsupportedTarget': message("This related destination is not supported yet."),
    'notifications.targetMissing': message("The related resource is missing or was deleted."),
    'notifications.targetDenied': message("Access to the related resource was denied."),
    'notifications.targetUnknown': message("Access to the related resource is unknown."),
    'notifications.invalidTime': message("Time unavailable"),
    'notifications.typeRender': message("Render update"),
    'notifications.typeReview': message("Review request"),
    'notifications.typeAnnouncement': message("Announcement"),
    'notifications.typeOther': message("Other notification"),
    'projects.region': message('Workspace recent projects'),
    'projects.eyebrow': message('Workspace · read-only'),
    'projects.title': message('Recent projects'),
    'projects.description': message('Find and inspect a bounded snapshot of recent work. This view cannot open, create, or change projects.'),
    'projects.originSimulated': message('SIMULATED PROJECT DATA · localhost fixture only · no real account or permission'),
    'projects.originReal': message('CONNECTED READ-ONLY SOURCE · access is supplied by the host application'),
    'projects.originUnavailable': message('PROJECT SOURCE UNAVAILABLE · no request was sent'),
    'projects.boundary': message('This is a recent snapshot, not a full project inventory. Project opening and creation remain unavailable.'),
    'projects.refresh': message('Refresh recent projects'),
    'projects.loadingTitle': message('Loading recent projects'),
    'projects.loadingLabel': message('Loading recent projects'),
    'projects.cancel': message('Cancel loading'),
    'projects.cancelledTitle': message('Recent project loading cancelled'),
    'projects.cancelledBody': message('Loading cancelled.'),
    'projects.retry': message('Retry loading'),
    'projects.failureUnavailableTitle': message('Recent projects unavailable'),
    'projects.failureUnavailableBody': message('No authenticated, session-bound recent-project source is configured for this view.'),
    'projects.failureDeniedTitle': message('Recent projects denied'),
    'projects.failureDeniedBody': message('The supplied effective-access projection denied this read-only request.'),
    'projects.failureUnknownTitle': message('Recent projects access unknown'),
    'projects.failureUnknownBody': message('Access could not be established, so the recent-project request remained fail-closed.'),
    'projects.failureUnsupportedTitle': message('Recent projects unsupported'),
    'projects.failureUnsupportedBody': message('The connected source does not support this bounded recent-project request.'),
    'projects.failureErrorTitle': message('Recent projects error'),
    'projects.failureErrorBody': message('The recent-project snapshot could not be validated or loaded.'),
    'projects.search': message('Search recent projects'),
    'projects.searchPlaceholder': message('Search name or description'),
    'projects.statusLabel': message('Projected status'),
    'projects.allStatuses': message('All projected statuses'),
    'projects.sortLabel': message('Sort recent projects'),
    'projects.sortAscending': message('Name A–Z'),
    'projects.sortDescending': message('Name Z–A'),
    'projects.snapshotLimited': message('{count} recent projects loaded · limited snapshot; more may exist.', ['count']),
    'projects.snapshotRecent': message('{count} recent projects loaded · bounded recent snapshot.', ['count']),
    'projects.emptyTitle': message('No recent projects in this snapshot'),
    'projects.emptyBody': message('The source returned an empty recent-work snapshot. This does not establish that the workspace has no projects.'),
    'projects.noMatchesTitle': message('No matching recent projects'),
    'projects.noMatchesBody': message('No item in the loaded recent snapshot matches the current local filters.'),
    'projects.reset': message('Reset filters'),
    'projects.list': message('Recent project snapshot'),
    'projects.noDescription': message('No description projected.'),
    'projects.statusUnknown': message('Status not projected'),
    'projects.inspect': message('Inspect'),
    'projects.inspectNamed': message('Inspect {name}', ['name']),
    'projects.detailTitle': message('Project details'),
    'projects.detailClose': message('Close project details'),
    'projects.detailReadOnly': message('Read-only local inspection'),
    'projects.detailId': message('Project ID'),
    'projects.detailStatus': message('Projected status'),
    'projects.detailCreated': message('Projected creation time'),
    'projects.notProjected': message('Not projected'),
    'projects.detailLimit': message('Inspection does not establish canonical availability or permission to open this project.'),
    'renders.region': message('Single-Project render summaries'),
    'renders.eyebrow': message('Operations · read-only'),
    'renders.title': message('Project renders'),
    'renders.description': message('Find and inspect safe render job summaries supplied for one explicit Project. This view cannot control jobs.'),
    'renders.originSimulated': message('SIMULATED RENDER DATA · localhost fixture only · no real account or permission'),
    'renders.originReal': message('CONNECTED READ-ONLY SOURCE · access and Project scope are supplied by the host application'),
    'renders.originUnavailable': message('RENDER SOURCE UNAVAILABLE · no request was sent'),
    'renders.projectId': message('Source Project ID'),
    'renders.boundary': message('Scope comes only from the source Project shown above. Results are bounded and are not a global render inventory.'),
    'renders.refresh': message('Refresh render summaries'),
    'renders.loadingTitle': message('Loading render summaries'),
    'renders.loadingLabel': message('Loading render summaries'),
    'renders.cancel': message('Cancel loading'),
    'renders.cancelledTitle': message('Render summary loading cancelled'),
    'renders.cancelledBody': message('Loading cancelled.'),
    'renders.retry': message('Retry loading'),
    'renders.failureUnavailableTitle': message('Render summaries unavailable'),
    'renders.failureUnavailableBody': message('No authenticated, session-bound, single-Project render source is configured for this view.'),
    'renders.failureDeniedTitle': message('Render summaries denied'),
    'renders.failureDeniedBody': message('The supplied effective-access projection denied this read-only request.'),
    'renders.failureUnknownTitle': message('Render summary access unknown'),
    'renders.failureUnknownBody': message('Access or Project scope could not be established, so the request remained fail-closed.'),
    'renders.failureUnsupportedTitle': message('Render summaries unsupported'),
    'renders.failureUnsupportedBody': message('The connected source does not support this bounded single-Project request.'),
    'renders.failureErrorTitle': message('Render summaries error'),
    'renders.failureErrorBody': message('The render summary result could not be validated or loaded.'),
    'renders.search': message('Search render summaries'),
    'renders.searchPlaceholder': message('Search render ID or profile'),
    'renders.statusLabel': message('Render status'),
    'renders.allStatuses': message('All established statuses'),
    'renders.sortLabel': message('Sort render summaries'),
    'renders.sortAscending': message('Render ID A–Z'),
    'renders.sortDescending': message('Render ID Z–A'),
    'renders.snapshotLimited': message('{count} render summaries loaded · limited Project snapshot; more may exist.', ['count']),
    'renders.snapshotBounded': message('{count} render summaries loaded · bounded Project snapshot.', ['count']),
    'renders.emptyTitle': message('No render summaries in this snapshot'),
    'renders.emptyBody': message('The source returned an empty bounded snapshot. This does not establish a global absence of render jobs.'),
    'renders.noMatchesTitle': message('No matching render summaries'),
    'renders.noMatchesBody': message('No item in the loaded Project snapshot matches the current local filters.'),
    'renders.reset': message('Reset filters'),
    'renders.list': message('Render summary snapshot'),
    'renders.inspect': message('Inspect'),
    'renders.inspectNamed': message('Inspect render {id}', ['id']),
    'renders.detailTitle': message('Render summary details'),
    'renders.detailClose': message('Close render summary details'),
    'renders.detailReadOnly': message('Read-only local inspection'),
    'renders.detailId': message('Render job ID'),
    'renders.detailProjectId': message('Project ID'),
    'renders.detailTimelineSnapshotId': message('Timeline snapshot ID'),
    'renders.detailProfile': message('Profile'),
    'renders.detailStatus': message('Status'),
    'renders.detailLimit': message('This safe summary does not expose job controls, execution authority, providers, workers, runtime details, artifacts, or downloads.'),
    brandHome: message('Media Platform home'), brand: message('Media Platform'), creativeWorkspace: message('Creative workspace'),
    globalNavigation: message('Global navigation'), projectNavigation: message('Project navigation'), projectSurfaceSwitcher: message('Project surface switcher'),
    workspace: message('Workspace'), operations: message('Operations'), admin: message('Admin'), developer: message('Developer'),
    overview: message('Overview'), review: message('Review'), production: message('Production'), panelControls: message('Panel controls'),
    navigation: message('Navigation'), navigationDrawerSurfaces: message('Navigation drawer surfaces'), toggleAssetBrowser: message('Toggle asset browser'),
    commands: message('Commands'), skipToMain: message('Skip to main content'), assetBrowser: message('Asset browser'), assets: message('Assets'),
    commandPalette: message('Command palette'), searchCommands: message('Search commands'), typeCommand: message('Type a command…'), noMatchingCommands: message('No matching commands.'),
    closeCommandPalette: message('Close command palette'),
    commandHiddenSurface: message('This surface is not discoverable at its current maturity.'),
    commandUnresolvedProject: message('A server-resolved Project context is required.'),
    commandMissingAccess: message('Effective access is not available from the server. This action is disabled.'),
    commandNavigationHelp: message('Use Up and Down to focus available commands; Home and End move to the first and last result. Press Enter or Space on a command to run it. Tab moves between controls; Escape closes.'),
    commandResultCount: message('{count} commands found; {available} available.', ['count', 'available']),
    commandUnavailable: message('This action is not ready here. A connected, authorized application flow is required.'), technicalDetails: message('Technical details'),
    'command.project.create': message('Create project'), 'command.render.open': message('Open render entry'),
    'command.timeline.operation.apply': message('Apply timeline operation'), 'command.canvas.reference.add': message('Add canvas reference'),
    'command.workflow.invoke': message('Invoke workflow'), 'command.agent.action.authorize': message('Authorize proposed action'),
    'command.review.merge.request': message('Request canonical merge'),
    assetsUnavailable: message('Media browsing is not available yet. No assets have been loaded.'), timelineActivity: message('Timeline / activity'),
    canonicalResults: message('Canonical command results will appear here when integrated.'), activityPanel: message('Activity panel'), activity: message('Activity'),
    activityUnavailable: message('No scoped activity projection is available for this view.'),
  },
  agent: {
    primaryOnly: message("Existing operations affect only the primary object. Other selected objects remain unchanged."),
    canonicalUnavailable: message("This change cannot be applied here yet. A connected server preview and confirmation flow is required; use the existing timeline advanced controls for supported operations."),
    localAxis: message("Local {axis}", ["axis"]),
    placementRange: message("Placement range: −2000 to 2000 local units."),
    simulatedTimeHelp: message("Time uses simulated steps, not decoded media time."),
    simulatedTime: message("{count} simulated steps{range}", ["count", "range"]),
    simulatedRange: message(" · range {range}", ["range"]),
    demonstration: message("Deterministic UX demonstration · no connected Agent planning"),
    localResult: message("Local presentation or read-only request only; no canonical mutation."),
    requestUnavailable: message("This request is unavailable in the current context. Preview again."),
    selectedClips: message("{count} selected clips", ["count"]),
    selectedObjects: message("{count} selected objects", ["count"]),
    adjustAudio: message("Adjust audio (demo)"),
    duplicate: message("Duplicate (demo)"),
    fixtureUnavailable: message("Synthetic fixture only; no connected authorized operation."),
    kindNODE: message("NODE"),
    kindCLIP: message("CLIP"),
    kindLANE: message("LANE"),
    kindLowerNODE: message("node"),
    kindLowerCLIP: message("clip"),
    kindLowerLANE: message("lane"),
    ask: message('Ask Agent'), title: message('Agent conversation'), close: message('Close Agent conversation'), body: message('Agent conversation body'),
    context: message('Agent context'), project: message('Project: {project}', ['project']), surface: message('Surface: {surface}', ['surface']),
    selection: message('Selection: {selection}', ['selection']), time: message('Time: {time}', ['time']), revisionPair: message('Revision pair: {pair}', ['pair']),
    noProject: message('No project selected'), none: message('None'), useCompact: message('Use compact sheet'), expand: message('Expand sheet'),
    details: message('Details and diagnostics'), proposal: message('Synthetic proposal'), syntheticDemo: message('Synthetic demo'),
    understoodRequest: message('Understood request'), noRequest: message('No request entered.'), targets: message('Targets'), proposedChange: message('Proposed change'),
    readOnlyAvailable: message('A read-only comparison can be run; it does not make a canonical change.'),
    localActionAvailable: message('This local presentation action is available now. It is not saved and does not make a canonical change.'),
    proposalUnavailable: message('Apply is unavailable for this proposal. Preview or modify the request; a connected confirmation flow is required before a canonical change.'),
    contextChanged: message('Context changed. Preview again for the current selection and time.'), modify: message('Modify'),
    runReadOnly: message('Run read-only comparison'), openInspector: message('Open Inspector'), applyLocal: message('Apply local presentation'),
    revealLocal: message('Reveal primary locally'), apply: message('Apply'), applyUnavailableA11y: message('Unavailable: this synthetic demo has no connected canonical confirmation flow.'),
    proposalDiagnostics: message('Proposal diagnostics'), userIntent: message('User intent'), intentPlaceholder: message('Try inspect, reveal, or rename to Opening shot'),
    preview: message('Preview'), clearConversation: message('Clear conversation'), composer: message('Agent composer'),
    selectionActions: message('Selection actions'), selectedPrimary: message('{count} selected · primary {kind} · {title}', ['count', 'kind', 'title']),
    singleSelection: message('{kind} · {title}', ['kind', 'title']), hideInspector: message('Hide inspector'), showInspector: message('Show inspector'),
    revealPrimary: message('Reveal primary {kind}', ['kind']), clearSelection: message('Clear selection'), more: message('More'),
    localOnly: message('Local presentation only · not saved'), editProperties: message('Edit local properties'), applyCanonical: message('Apply canonical change'),
    technicalDetails: message('Technical details'), localNodeInspector: message('Local node inspector'), presentationSelection: message('Presentation selection'),
    syntheticFixture: message('Synthetic fixture · no canonical clip geometry.'), localPresentationLifetime: message('Local presentation · changes last until you leave this surface or project.'),
    selectedObject: message('Selected object'), selectedTargets: message('Selected targets'), selectedTrack: message('Selected track'), localTitle: message('Local title'),
    reference: message('Reference'), simulationStep: message('Simulation step'), showPrimaryNode: message('Show primary node'), clearTrackSelection: message('Clear track selection'),
    selectionInspector: message('Selection inspector'), openSelectionProperties: message('Open selection properties'), selectionProperties: message('Selection properties'),
    commandInspect: message('Inspect {target}', ['target']), commandReveal: message('Reveal {target}', ['target']), commandAsk: message('Ask Agent about {target}', ['target']), commandCompare: message('What changed between these revisions?'),
  },
  canvas: {
    selectMode: message("Select"), panMode: message("Pan"),
    pointerHelp: message("Select: drag empty space to select nodes. Drag at least 4 screen pixels with width and height; Ctrl or Meta adds to selection. Pan: drag empty space to move the view. Drag a selected node to move its group locally; release to finish. Escape cancels a gesture. Keyboard and Multi-select controls remain available."),
    dragPreview: message("Local move preview; release to place."), marqueePreview: message("Selection preview; release to select."), panPreview: message("View preview; release to pan."),
    multiSelect: message("Multi-select"),
    done: message("Done"),
    controls: message("Canvas controls · local changes only"),
    keyboardHelp: message("On the canvas, arrows pan and =/− zoom. Tab focuses nodes; Enter or Space selects. Ctrl/Meta click or Enter/Space toggles selection. Multi-select mode toggles with taps; Done returns to single selection. On a node, arrows move only that node 24 local units and preserve selected membership. R reveals the primary. Escape clears selection. Visual guides never create semantic relationships."),
    relationshipUnavailable: message("No canonical relationship command is integrated."),
    relationship: message("Create semantic relationship"),
    untitledNode: message("Untitled local node"),
    noReference: message("No semantic reference"),
    visualOnly: message("visual only"),
    selectionStatus: message("{count} selected · primary: {title}", ["count", "title"]),
    viewportStatus: message("Viewport: {x}, {y}", ["x", "y"]),
    viewportControls: message("Canvas viewport controls"),
    fit: message("Fit canvas"),
    moreViewport: message("More viewport controls"),
    panLeft: message("Pan left"),
    panRight: message("Pan right"),
    panUp: message("Pan up"),
    panDown: message("Pan down"),
    zoomOut: message("Zoom out"),
    zoomIn: message("Zoom in"),
    resetViewport: message("Reset viewport"),
    eyebrow: message('Creative · Canvas'), title: message('Infinite canvas'), description: message('Arrange ideas around your project. Local changes are not saved.'),
    workspace: message('Infinite canvas workspace'), localComposition: message('Local composition'),
  },
  timeline: {
    eyebrow: message('Creative · NLE'), title: message('Timeline editor'), description: message('Explore the timeline and preview changes before applying them.'),
    workspace: message('Timeline workspace'), playbackControls: message('Timeline playback controls'), keyboardControls: message('Timeline keyboard controls'),
  },
  review: {
    "overview": message("Overview"),
    "visual": message("Visual Changes"),
    "conversation": message("Conversation"),
    "checks": message("Checks"),
    "projectDetails": message("Project and workspace IDs"),
    "workspaceId": message("Workspace ID"),
    "projectId": message("Project ID"),
    "sections": message("Review sections"),
    "direction": message("From is the starting revision; To is the revision you compare it with. Choose the order, then compare. Reversing the pair changes the direction. This view does not apply or merge changes."),
    "history": message("Revision history"),
    "loadingHistory": message("Loading revision history…"),
    "loadingChoices": message("Loading revision choices and change summary"),
    "historyFailed": message("We couldn’t load revision history."),
    "historyRetryHelp": message("Try again to choose revisions."),
    "historyBlockedHelp": message("Retry is unavailable for this response. Check access or project availability before returning to Review."),
    "retryHistory": message("Retry history"),
    "noRevisions": message("No revisions available"),
    "noRevisionsHelp": message("No revisions were returned for this project. Comparison needs two distinct revisions."),
    "refreshHistory": message("Refresh history"),
    "oneRevision": message("Only one distinct revision is available. Comparison needs two."),
    "from": message("From revision"),
    "to": message("To revision"),
    "selectRevision": message("Select revision"),
    "comparing": message("Comparing…"),
    "retryComparison": message("Retry comparison"),
    "compare": message("Compare revisions"),
    "mergeDisabled": message("Merge unavailable"),
    "selectedPair": message("Selected revision pair"),
    "requestedPair": message("Requested revision pair"),
    "pairDetails": message("Revision IDs"),
    "comparisonFailed": message("We couldn’t compare these revisions."),
    "comparisonRetryHelp": message("Retry comparison above."),
    "comparisonBlockedHelp": message("Retry is unavailable for this pair. Check access or choose a different pair."),
    "loadingComparison": message("Loading revision comparison…"),
    "loaded": message("Comparison loaded."),
    "loadedNoEntities": message("Comparison loaded; no entity details were returned."),
    "needsHistory": message("Comparison needs two distinct revisions from the available history."),
    "chooseBoth": message("Choose a From revision and a To revision."),
    "chooseFrom": message("Choose a From revision."),
    "chooseTo": message("Choose a To revision."),
    "chooseDifferent": message("Choose different revisions; the current pair is the same revision."),
    "chooseKnown": message("Choose revisions from the available history."),
    "ready": message("Ready to compare. Select Compare revisions to load changes in this order."),
    "revisionNumber": message("Revision {number}", ["number"]),
    "technical": message("Technical details"),
    "comparisonTechnical": message("Comparison technical details"),
    "serverComparison": message("Server comparison"),
    "failureMismatch": message("The returned comparison does not match the requested revision pair."),
    "sectionUnavailable": message("{section} unavailable", ["section"]),
    "sectionUnavailableHelp": message("This review section is not available yet."),
    "failure.STALE_BASE_REVISION": message("The starting revision is no longer current."),
    "failure.STALE_TARGET_REF": message("The target reference has changed."),
    "failure.PLAN_CHANGED": message("The server plan has changed."),
    "failure.AUTHORIZATION_DENIED": message("You do not have permission for this request."),
    "failure.AUTHORIZATION_CONTEXT_MISMATCH": message("The authorization context does not match this request."),
    "failure.TENANT_CONTEXT_MISMATCH": message("The tenant context does not match this request."),
    "failure.UNAUTHENTICATED": message("Sign in to access this request."),
    "failure.VALIDATION": message("The request or server response could not be validated."),
    "failure.UNSUPPORTED": message("The server does not support this request."),
    "failure.CONFLICT": message("A conflict prevented this request."),
    "failure.NOT_FOUND": message("The requested revisions or project are not available."),
    "failure.UNAVAILABLE": message("The comparison service is temporarily unavailable."),
    "failure.NETWORK": message("A network problem prevented loading."),
    "failure.UNKNOWN": message("The request failed for an unrecognized reason."),
    "diff.all": message("All actions"),
    "diff.added": message("Added"),
    "diff.removed": message("Removed"),
    "diff.modified": message("Modified"),
    "diff.clip": message("Clip"),
    "diff.track": message("Track"),
    "diff.asset": message("Asset"),
    "diff.notLoaded": message("No server comparison loaded"),
    "diff.notLoadedHelp": message("Choose two revisions and compare to see their changes."),
    "diff.resultPair": message("Server result revision pair"),
    "diff.action": message("Action"),
    "diff.server": message("Server comparison"),
    "diff.limited": message("Server summary limited"),
    "diff.summary": message("Server change summary"),
    "diff.tracks": message("Tracks added / removed / changed"),
    "diff.clips": message("Clips added / removed / changed"),
    "diff.assets": message("Assets added / removed"),
    "diff.unsupported": message("Summary unavailable"),
    "diff.unsupportedHelp": message("The server does not support a summary for this pair. This does not mean there are no changes. Any returned entity details appear below."),
    "diff.filteredEmpty": message("No matching entity changes"),
    "diff.filteredEmptyHelp": message("No returned entities match this action filter. Choose All actions to see every returned entity."),
    "diff.zero": message("No changes reported"),
    "diff.zeroHelp": message("The supported server summary reports zero in every counter and returns no entity changes."),
    "diff.noEntities": message("No entity details returned"),
    "diff.noEntitiesHelp": message("The server returned no entity details for this pair. This does not establish that there are no changes."),

    eyebrow: message('Review & collaboration'), title: message('Project review'), description: message('Choose two revisions to see what changed. Review does not apply or merge changes.'),
    panel: message('Semantic Changes'), missingInZh: message('English fallback proof'),
  },
  workflow: {},
  render: {},
  settings: {},
  errors: {},
}

const chineseNamespaces: CatalogNamespaces = {
  common: {
    greeting: message('你好，{name}', ['name']), untitled: message('未命名'), none: message('无'),
    localeSelector: message('产品界面语言'), localeEnglish: message('English'), localeChinese: message('简体中文'),
  },
  shell: {
    'notifications.title': message("通知"),
    'notifications.close': message("关闭通知"),
    'notifications.entryUnknown': message("通知 · 未读数量未知"),
    'notifications.entryCount': message("通知 · 收件箱有 {count} 条未读", ["count"]),
    'notifications.simulatedBadge': message("模拟数据"),
    'notifications.simulated': message("模拟数据 · 仅为内存中的示例。未连接真实账户、通知或权限。"),
    'notifications.real': message("已连接收件箱来源。目标访问权限将单独检查。"),
    'notifications.originUnavailable': message("收件箱尚未连接。"),
    'notifications.unavailable': message("通知尚未连接。未读数量未知。"),
    'notifications.filter': message("筛选通知"),
    'notifications.all': message("全部"),
    'notifications.unread': message("未读"),
    'notifications.read': message("已读"),
    'notifications.refresh': message("刷新通知"),
    'notifications.readAll': message("将整个收件箱标为已读"),
    'notifications.readAllScope': message("作用于整个收件箱，包括当前快照和筛选之外的通知。"),
    'notifications.readAllUnsupported': message("此来源不支持将整个收件箱标为已读。"),
    'notifications.singleUnsupported': message("此来源不支持将单条通知标为已读。"),
    'notifications.loading': message("正在加载通知…"),
    'notifications.loaded': message("通知快照已加载。"),
    'notifications.empty': message("此快照中没有通知。"),
    'notifications.denied': message("收件箱访问被拒绝。"),
    'notifications.error': message("无法加载通知。请刷新后重试。"),
    'notifications.notFound': message("此通知已不可用。请刷新收件箱。"),
    'notifications.marking': message("正在等待已读确认…"),
    'notifications.readError': message("无法确认通知已读。请刷新后重试。"),
    'notifications.readConfirmed': message("已确认已读，已重新请求收件箱。"),
    'notifications.partialRead': message("部分通知无法标为已读，已重新请求收件箱。"),
    'notifications.globalCount': message("整个收件箱共有 {count} 条未读。", ["count"]),
    'notifications.unknownCount': message("未读数量未知。已加载条目数不是收件箱总数。"),
    'notifications.limited': message("当前仅显示有限快照，可能还有更多通知。"),
    'notifications.complete': message("此快照已返回符合当前筛选的全部通知。"),
    'notifications.list': message("通知列表"),
    'notifications.untitled': message("无标题通知"),
    'notifications.readDetail': message("阅读通知：{title}", ["title"]),
    'notifications.markRead': message("标为已读"),
    'notifications.detail': message("通知详情"),
    'notifications.openResource': message("打开相关资源"),
    'notifications.simulatedTarget': message("打开模拟项目概览，不授予真实账号或资源权限。"),
    'notifications.destinationChecks': message("目标页面将检查当前资源访问权限。此通知不授予权限。"),
    'notifications.unsupportedTarget': message("尚不支持此相关目标。"),
    'notifications.targetMissing': message("相关资源不存在或已删除。"),
    'notifications.targetDenied': message("相关资源的访问被拒绝。"),
    'notifications.targetUnknown': message("相关资源的访问权限未知。"),
    'notifications.invalidTime': message("时间不可用"),
    'notifications.typeRender': message("渲染更新"),
    'notifications.typeReview': message("审阅请求"),
    'notifications.typeAnnouncement': message("公告"),
    'notifications.typeOther': message("其他通知"),
    'projects.region': message('工作区最近项目'),
    'projects.eyebrow': message('工作区 · 只读'),
    'projects.title': message('最近项目'),
    'projects.description': message('查找并检查有限的最近工作快照。此视图不能打开、创建或更改项目。'),
    'projects.originSimulated': message('模拟项目数据 · 仅限 localhost 固定数据 · 未连接真实账户或权限'),
    'projects.originReal': message('已连接只读来源 · 访问权限由宿主应用提供'),
    'projects.originUnavailable': message('项目来源不可用 · 未发送请求'),
    'projects.boundary': message('这是最近项目快照，并非完整项目清单。项目打开和创建功能仍不可用。'),
    'projects.refresh': message('刷新最近项目'),
    'projects.loadingTitle': message('正在加载最近项目'),
    'projects.loadingLabel': message('正在加载最近项目'),
    'projects.cancel': message('取消加载'),
    'projects.cancelledTitle': message('最近项目加载已取消'),
    'projects.cancelledBody': message('加载已取消。'),
    'projects.retry': message('重试加载'),
    'projects.failureUnavailableTitle': message('最近项目不可用'),
    'projects.failureUnavailableBody': message('此视图尚未配置经过身份验证且绑定会话的最近项目来源。'),
    'projects.failureDeniedTitle': message('最近项目访问被拒绝'),
    'projects.failureDeniedBody': message('提供的有效访问权限投影拒绝了此只读请求。'),
    'projects.failureUnknownTitle': message('最近项目访问权限未知'),
    'projects.failureUnknownBody': message('无法确定访问权限，因此最近项目请求保持关闭。'),
    'projects.failureUnsupportedTitle': message('不支持最近项目'),
    'projects.failureUnsupportedBody': message('已连接来源不支持此有限的最近项目请求。'),
    'projects.failureErrorTitle': message('最近项目错误'),
    'projects.failureErrorBody': message('无法验证或加载最近项目快照。'),
    'projects.search': message('搜索最近项目'),
    'projects.searchPlaceholder': message('搜索名称或描述'),
    'projects.statusLabel': message('投影状态'),
    'projects.allStatuses': message('所有投影状态'),
    'projects.sortLabel': message('最近项目排序'),
    'projects.sortAscending': message('名称 A–Z'),
    'projects.sortDescending': message('名称 Z–A'),
    'projects.snapshotLimited': message('已加载 {count} 个最近项目 · 有限快照，可能还有更多项目。', ['count']),
    'projects.snapshotRecent': message('已加载 {count} 个最近项目 · 有限的最近快照。', ['count']),
    'projects.emptyTitle': message('此快照中没有最近项目'),
    'projects.emptyBody': message('来源返回了空的最近工作快照。这不能证明工作区中没有项目。'),
    'projects.noMatchesTitle': message('没有匹配的最近项目'),
    'projects.noMatchesBody': message('已加载的最近快照中没有条目匹配当前本地筛选条件。'),
    'projects.reset': message('重置筛选条件'),
    'projects.list': message('最近项目快照'),
    'projects.noDescription': message('未投影描述。'),
    'projects.statusUnknown': message('未投影状态'),
    'projects.inspect': message('检查'),
    'projects.inspectNamed': message('检查 {name}', ['name']),
    'projects.detailTitle': message('项目详情'),
    'projects.detailClose': message('关闭项目详情'),
    'projects.detailReadOnly': message('只读本地检查'),
    'projects.detailId': message('项目 ID'),
    'projects.detailStatus': message('投影状态'),
    'projects.detailCreated': message('投影创建时间'),
    'projects.notProjected': message('未投影'),
    'projects.detailLimit': message('检查不会建立规范可用性，也不会授予打开此项目的权限。'),
    'renders.region': message('单项目渲染摘要'),
    'renders.eyebrow': message('运营 · 只读'),
    'renders.title': message('项目渲染'),
    'renders.description': message('查找并检查来源为一个明确项目提供的安全渲染任务摘要。此视图不能控制任务。'),
    'renders.originSimulated': message('模拟渲染数据 · 仅限 localhost 固定数据 · 未连接真实账户或权限'),
    'renders.originReal': message('已连接只读来源 · 访问权限和项目范围由宿主应用提供'),
    'renders.originUnavailable': message('渲染来源不可用 · 未发送请求'),
    'renders.projectId': message('来源项目 ID'),
    'renders.boundary': message('范围仅来自上方显示的来源项目。结果数量有限，并非全局渲染清单。'),
    'renders.refresh': message('刷新渲染摘要'),
    'renders.loadingTitle': message('正在加载渲染摘要'),
    'renders.loadingLabel': message('正在加载渲染摘要'),
    'renders.cancel': message('取消加载'),
    'renders.cancelledTitle': message('渲染摘要加载已取消'),
    'renders.cancelledBody': message('加载已取消。'),
    'renders.retry': message('重试加载'),
    'renders.failureUnavailableTitle': message('渲染摘要不可用'),
    'renders.failureUnavailableBody': message('此视图尚未配置经过身份验证、绑定会话且限定单一项目的渲染来源。'),
    'renders.failureDeniedTitle': message('渲染摘要访问被拒绝'),
    'renders.failureDeniedBody': message('提供的有效访问权限投影拒绝了此只读请求。'),
    'renders.failureUnknownTitle': message('渲染摘要访问权限未知'),
    'renders.failureUnknownBody': message('无法确定访问权限或项目范围，因此请求保持关闭。'),
    'renders.failureUnsupportedTitle': message('不支持渲染摘要'),
    'renders.failureUnsupportedBody': message('已连接来源不支持此有限的单项目请求。'),
    'renders.failureErrorTitle': message('渲染摘要错误'),
    'renders.failureErrorBody': message('无法验证或加载渲染摘要结果。'),
    'renders.search': message('搜索渲染摘要'),
    'renders.searchPlaceholder': message('搜索渲染 ID 或配置'),
    'renders.statusLabel': message('渲染状态'),
    'renders.allStatuses': message('所有已建立状态'),
    'renders.sortLabel': message('渲染摘要排序'),
    'renders.sortAscending': message('渲染 ID A–Z'),
    'renders.sortDescending': message('渲染 ID Z–A'),
    'renders.snapshotLimited': message('已加载 {count} 个渲染摘要 · 有限项目快照，可能还有更多结果。', ['count']),
    'renders.snapshotBounded': message('已加载 {count} 个渲染摘要 · 有限项目快照。', ['count']),
    'renders.emptyTitle': message('此快照中没有渲染摘要'),
    'renders.emptyBody': message('来源返回了空的有限快照。这不能证明全局不存在渲染任务。'),
    'renders.noMatchesTitle': message('没有匹配的渲染摘要'),
    'renders.noMatchesBody': message('已加载的项目快照中没有条目匹配当前本地筛选条件。'),
    'renders.reset': message('重置筛选条件'),
    'renders.list': message('渲染摘要快照'),
    'renders.inspect': message('检查'),
    'renders.inspectNamed': message('检查渲染 {id}', ['id']),
    'renders.detailTitle': message('渲染摘要详情'),
    'renders.detailClose': message('关闭渲染摘要详情'),
    'renders.detailReadOnly': message('只读本地检查'),
    'renders.detailId': message('渲染任务 ID'),
    'renders.detailProjectId': message('项目 ID'),
    'renders.detailTimelineSnapshotId': message('时间线快照 ID'),
    'renders.detailProfile': message('配置'),
    'renders.detailStatus': message('状态'),
    'renders.detailLimit': message('此安全摘要不提供任务控制、执行权限、提供方、工作器、运行时详情、制品或下载。'),
    brandHome: message('媒体平台首页'), brand: message('媒体平台'), creativeWorkspace: message('创作工作区'),
    globalNavigation: message('全局导航'), projectNavigation: message('项目导航'), projectSurfaceSwitcher: message('项目界面切换'),
    workspace: message('工作区'), operations: message('运营'), admin: message('管理'), developer: message('开发者'), overview: message('概览'), review: message('审阅'),
    production: message('制作'), panelControls: message('面板控件'), navigation: message('导航'), navigationDrawerSurfaces: message('导航抽屉界面'),
    toggleAssetBrowser: message('切换素材浏览器'), commands: message('命令'), skipToMain: message('跳到主要内容'), assetBrowser: message('素材浏览器'),
    commandPalette: message('命令面板'), searchCommands: message('搜索命令'), typeCommand: message('输入命令…'), noMatchingCommands: message('没有匹配的命令。'),
    closeCommandPalette: message('关闭命令面板'),
    commandHiddenSurface: message('此界面在当前成熟度下尚未开放。'),
    commandUnresolvedProject: message('需要服务器已解析的项目上下文。'),
    commandMissingAccess: message('服务器尚未提供有效访问权限信息。此操作已禁用。'),
    commandNavigationHelp: message('使用上、下方向键聚焦可用命令；在命令上使用 Home 和 End 移至首个和末个结果。按 Enter 或空格执行聚焦的命令。Tab 切换控件；Escape 关闭面板。'),
    commandResultCount: message('找到 {count} 个命令；{available} 个可用。', ['count', 'available']),
    commandUnavailable: message('此操作尚未就绪，需要已连接且获授权的应用流程。'), technicalDetails: message('技术详情'),
    'command.project.create': message('创建项目'), 'command.render.open': message('打开渲染入口'),
    'command.timeline.operation.apply': message('应用时间线操作'), 'command.canvas.reference.add': message('添加画布引用'),
    'command.workflow.invoke': message('调用工作流'), 'command.agent.action.authorize': message('授权拟议操作'),
    'command.review.merge.request': message('请求规范合并'),
    assets: message('素材'), assetsUnavailable: message('媒体浏览暂不可用。尚未加载素材。'), timelineActivity: message('时间线 / 活动'),
    canonicalResults: message('接入后，规范命令结果将显示在这里。'), activityPanel: message('活动面板'), activity: message('活动'),
    activityUnavailable: message('此视图暂无限定范围的活动投影。'),
  },
  agent: {
    primaryOnly: message("现有操作仅影响主要对象。其他所选对象保持不变。"),
    canonicalUnavailable: message("此处尚无法应用此更改。需要已连接的服务器预览和确认流程。"),
    localAxis: message("本地 {axis}", ["axis"]),
    placementRange: message("放置范围：−2000 至 2000 个本地单位。"),
    simulatedTimeHelp: message("时间使用模拟步骤，并非解码媒体时间。"),
    simulatedTime: message("{count} 个模拟步骤{range}", ["count", "range"]),
    simulatedRange: message(" · 范围 {range}", ["range"]),
    demonstration: message("确定性界面演示 · 未连接 Agent 规划"),
    localResult: message("仅本地呈现或只读请求；无规范更改。"),
    requestUnavailable: message("当前上下文中此请求不可用。请重新预览。"),
    selectedClips: message("已选择的 {count} 个片段", ["count"]),
    selectedObjects: message("已选择的 {count} 个对象", ["count"]),
    adjustAudio: message("调整音频（演示）"),
    duplicate: message("复制（演示）"),
    fixtureUnavailable: message("仅模拟夹具；未连接获授权的操作。"),
    kindNODE: message("节点"),
    kindCLIP: message("片段"),
    kindLANE: message("轨道"),
    kindLowerNODE: message("节点"),
    kindLowerCLIP: message("片段"),
    kindLowerLANE: message("轨道"),
    ask: message('询问 Agent'), title: message('Agent 对话'), close: message('关闭 Agent 对话'), body: message('Agent 对话内容'), context: message('Agent 上下文'),
    project: message('项目：{project}', ['project']), surface: message('界面：{surface}', ['surface']), selection: message('选择：{selection}', ['selection']),
    time: message('时间：{time}', ['time']), revisionPair: message('修订对：{pair}', ['pair']), noProject: message('未选择项目'), none: message('无'),
    useCompact: message('使用紧凑面板'), expand: message('展开面板'), details: message('详情与诊断'), proposal: message('模拟提案'), syntheticDemo: message('模拟演示'),
    understoodRequest: message('已理解的请求'), noRequest: message('未输入请求。'), targets: message('目标'), proposedChange: message('拟议更改'),
    readOnlyAvailable: message('可以运行只读比较；它不会进行规范更改。'), localActionAvailable: message('此本地呈现操作现已可用。它不会保存，也不会进行规范更改。'),
    proposalUnavailable: message('此提案无法应用。请预览或修改请求；规范更改前需要已连接的确认流程。'),
    contextChanged: message('上下文已变化。请针对当前选择和时间重新预览。'), modify: message('修改'), runReadOnly: message('运行只读比较'),
    openInspector: message('打开检查器'), applyLocal: message('应用本地呈现'), revealLocal: message('在本地显示主要对象'), apply: message('应用'),
    applyUnavailableA11y: message('不可用：此模拟演示未连接规范确认流程。'), proposalDiagnostics: message('提案诊断'), userIntent: message('用户意图'),
    intentPlaceholder: message('描述要检查或更改的内容'), preview: message('预览'), clearConversation: message('清除对话'), composer: message('Agent 编辑器'),
    selectionActions: message('选择操作'), selectedPrimary: message('已选择 {count} 个 · 主要 {kind} · {title}', ['count', 'kind', 'title']),
    singleSelection: message('{kind} · {title}', ['kind', 'title']), hideInspector: message('隐藏检查器'), showInspector: message('显示检查器'),
    revealPrimary: message('显示主要{kind}', ['kind']), clearSelection: message('清除选择'), more: message('更多'), localOnly: message('仅本地呈现 · 未保存'),
    editProperties: message('编辑本地属性'), applyCanonical: message('应用规范更改'), technicalDetails: message('技术详情'), localNodeInspector: message('本地节点检查器'),
    presentationSelection: message('呈现选择'), syntheticFixture: message('模拟夹具 · 无规范片段几何信息。'),
    localPresentationLifetime: message('本地呈现 · 离开此界面或项目后更改失效。'), selectedObject: message('所选对象'), selectedTargets: message('所选目标'),
    selectedTrack: message('所选轨道'), localTitle: message('本地标题'), reference: message('引用'), simulationStep: message('模拟步骤'),
    showPrimaryNode: message('显示主要节点'), clearTrackSelection: message('清除轨道选择'), selectionInspector: message('选择检查器'),
    openSelectionProperties: message('打开选择属性'), selectionProperties: message('选择属性'),
    commandInspect: message('检查{target}', ['target']), commandReveal: message('显示{target}', ['target']), commandAsk: message('就{target}询问 Agent', ['target']), commandCompare: message('这些修订之间有什么变化？'),
  },
  canvas: {
    selectMode: message("选择"), panMode: message("平移"),
    pointerHelp: message("选择：在空白处拖动以选择节点。拖动至少 4 个屏幕像素并形成宽和高；Ctrl 或 Meta 添加选择。平移：在空白处拖动以移动视图。拖动已选节点可在本地移动整组；松开完成。Escape 取消手势。仍可使用键盘和多选控件。"),
    dragPreview: message("本地移动预览；松开以放置。"), marqueePreview: message("选择预览；松开以选择。"), panPreview: message("视图预览；松开以平移。"),
    multiSelect: message("多选"),
    done: message("完成"),
    controls: message("画布控件 · 仅本地更改"),
    keyboardHelp: message("在画布上，方向键平移，=/− 缩放。Tab 聚焦节点；Enter 或空格选择。Ctrl/Meta 点击或 Enter/空格切换选择。多选模式下轻点切换选择；完成后恢复单选。节点上的方向键仅移动该节点 24 个本地单位并保留已有选择。R 显示主要对象。Escape 清除选择。视觉辅助线不创建语义关系。"),
    relationshipUnavailable: message("尚未接入规范关系命令。"),
    relationship: message("创建语义关系"),
    untitledNode: message("未命名本地节点"),
    noReference: message("无语义引用"),
    visualOnly: message("仅视觉"),
    selectionStatus: message("已选择 {count} 个 · 主要对象：{title}", ["count", "title"]),
    viewportStatus: message("视口：{x}, {y}", ["x", "y"]),
    viewportControls: message("画布视口控件"),
    fit: message("适应画布"),
    moreViewport: message("更多视口控件"),
    panLeft: message("向左平移"),
    panRight: message("向右平移"),
    panUp: message("向上平移"),
    panDown: message("向下平移"),
    zoomOut: message("缩小"),
    zoomIn: message("放大"),
    resetViewport: message("重置视口"), eyebrow: message('创作 · 画布'), title: message('无限画布'), description: message('排列本地呈现节点，而不更改规范媒体。'), workspace: message('无限画布工作区'), localComposition: message('本地合成') },
  timeline: { eyebrow: message('创作 · 非线性编辑'), title: message('时间线编辑器'), description: message('浏览时间线，并在应用前预览更改。'), workspace: message('时间线工作区'), playbackControls: message('时间线播放控件'), keyboardControls: message('时间线键盘控件') },
  review: {
    "overview": message("概览"),
    "visual": message("视觉更改"),
    "conversation": message("讨论"),
    "checks": message("检查"),
    "projectDetails": message("项目与工作区标识"),
    "workspaceId": message("工作区标识"),
    "projectId": message("项目标识"),
    "sections": message("审阅分区"),
    "direction": message("起始修订是比较的出发点，目标修订是与其比较的版本。选择顺序后再比较；交换修订会改变比较方向。此视图不会应用或合并更改。"),
    "history": message("修订历史"),
    "loadingHistory": message("正在加载修订历史…"),
    "loadingChoices": message("正在加载修订选项与更改摘要"),
    "historyFailed": message("无法加载修订历史。"),
    "historyRetryHelp": message("请重试以选择修订。"),
    "historyBlockedHelp": message("此响应不允许重试。请确认访问权限或项目可用性后返回审阅。"),
    "retryHistory": message("重试加载历史"),
    "noRevisions": message("暂无修订"),
    "noRevisionsHelp": message("服务器未返回此项目的修订。比较需要两个不同的修订。"),
    "refreshHistory": message("刷新历史"),
    "oneRevision": message("仅有一个不同的修订。比较需要两个修订。"),
    "from": message("起始修订"),
    "to": message("目标修订"),
    "selectRevision": message("选择修订"),
    "comparing": message("正在比较…"),
    "retryComparison": message("重试比较"),
    "compare": message("比较修订"),
    "mergeDisabled": message("合并暂不可用"),
    "selectedPair": message("已选修订对"),
    "requestedPair": message("正在请求的修订对"),
    "pairDetails": message("修订标识"),
    "comparisonFailed": message("无法比较这些修订。"),
    "comparisonRetryHelp": message("请使用上方按钮重试比较。"),
    "comparisonBlockedHelp": message("此修订对不允许重试。请确认访问权限或选择其他修订对。"),
    "loadingComparison": message("正在加载修订比较…"),
    "loaded": message("比较已加载。"),
    "loadedNoEntities": message("比较已加载，未返回实体详情。"),
    "needsHistory": message("请先获取包含两个不同修订的历史。"),
    "chooseBoth": message("请选择起始修订和目标修订。"),
    "chooseFrom": message("请选择起始修订。"),
    "chooseTo": message("请选择目标修订。"),
    "chooseDifferent": message("请选择不同修订；当前两项为同一修订。"),
    "chooseKnown": message("请从可用历史中选择修订。"),
    "ready": message("已准备好比较。点击“比较修订”以按此顺序加载更改。"),
    "revisionNumber": message("修订 {number}", ["number"]),
    "technical": message("技术详情"),
    "comparisonTechnical": message("比较技术详情"),
    "serverComparison": message("服务器比较"),
    "failureMismatch": message("返回的比较与请求的修订对不匹配。"),
    "sectionUnavailable": message("{section}暂不可用", ["section"]),
    "sectionUnavailableHelp": message("此审阅分区尚未开放。"),
    "failure.STALE_BASE_REVISION": message("起始修订已不是当前版本。"),
    "failure.STALE_TARGET_REF": message("目标引用已更改。"),
    "failure.PLAN_CHANGED": message("服务器计划已更改。"),
    "failure.AUTHORIZATION_DENIED": message("您没有权限执行此请求。"),
    "failure.AUTHORIZATION_CONTEXT_MISMATCH": message("授权上下文与此请求不匹配。"),
    "failure.TENANT_CONTEXT_MISMATCH": message("租户上下文与此请求不匹配。"),
    "failure.UNAUTHENTICATED": message("请登录以访问此请求。"),
    "failure.VALIDATION": message("无法验证请求或服务器响应。"),
    "failure.UNSUPPORTED": message("服务器不支持此请求。"),
    "failure.CONFLICT": message("冲突阻止了此请求。"),
    "failure.NOT_FOUND": message("请求的修订或项目不可用。"),
    "failure.UNAVAILABLE": message("比较服务暂时不可用。"),
    "failure.NETWORK": message("网络问题导致加载失败。"),
    "failure.UNKNOWN": message("请求因未知原因失败。"),
    "diff.all": message("全部操作"),
    "diff.added": message("新增"),
    "diff.removed": message("移除"),
    "diff.modified": message("修改"),
    "diff.clip": message("片段"),
    "diff.track": message("轨道"),
    "diff.asset": message("素材"),
    "diff.notLoaded": message("尚未加载服务器比较"),
    "diff.notLoadedHelp": message("请选择两个修订并比较，以查看更改。"),
    "diff.resultPair": message("服务器结果修订对"),
    "diff.action": message("操作"),
    "diff.server": message("服务器比较"),
    "diff.limited": message("服务器摘要受限"),
    "diff.summary": message("服务器更改摘要"),
    "diff.tracks": message("新增 / 移除 / 修改轨道"),
    "diff.clips": message("新增 / 移除 / 修改片段"),
    "diff.assets": message("新增 / 移除素材"),
    "diff.unsupported": message("摘要不可用"),
    "diff.unsupportedHelp": message("服务器不支持此修订对的摘要。这并不表示没有更改。返回的实体详情显示在下方。"),
    "diff.filteredEmpty": message("没有匹配的实体更改"),
    "diff.filteredEmptyHelp": message("返回的实体中没有匹配此操作筛选的项。选择“全部操作”查看所有返回的实体。"),
    "diff.zero": message("未报告更改"),
    "diff.zeroHelp": message("服务器支持的摘要中所有计数均为零，且未返回实体更改。"),
    "diff.noEntities": message("未返回实体详情"),
    "diff.noEntitiesHelp": message("服务器未返回此修订对的实体详情。这不能证明没有更改。"),
 eyebrow: message('创作 · 审阅'), title: message('审阅工作区'), description: message('选择两个修订以查看更改。审阅不会应用或合并更改。'), panel: message('语义更改') },
  workflow: {}, render: {}, settings: {}, errors: {},
}

const bundledCatalogs = {
  en: createCatalog('en', englishNamespaces),
  'zh-CN': createCatalog('zh-CN', chineseNamespaces),
} as const

export class BundledCatalogProvider {
  getCatalog(locale: SupportedLocale): LocalizationCatalog {
    return bundledCatalogs[locale]
  }

  getSourceCatalog(): LocalizationCatalog {
    return bundledCatalogs.en
  }
}

export const defaultBundledCatalogProvider = new BundledCatalogProvider()

function sameParameters(actual: readonly string[], expected: readonly string[]): boolean {
  const left = [...actual].sort()
  const right = [...expected].sort()
  return left.length === right.length && left.every((parameter, index) => parameter === right[index])
}

export function validatePlatformCatalogContract(catalog: LocalizationCatalog): ValidationResult<LocalizationCatalog> {
  const source = defaultBundledCatalogProvider.getSourceCatalog()
  for (const [namespace, messages] of Object.entries(catalog.namespaces)) {
    for (const [key, definition] of Object.entries(messages)) {
      const fullKey = `${namespace}.${key}`
      const sourceDefinition = messageAt(source, fullKey)
      if (!sourceDefinition) return { ok: false, error: `${fullKey}: key is not platform owned` }
      if (!sameParameters(definition.params, sourceDefinition.params)) return { ok: false, error: `${fullKey}: parameter contract differs from platform source` }
    }
  }
  return { ok: true, value: catalog }
}

export function validatePlatformParameterContracts(contracts: Readonly<Record<string, readonly string[]>>): ValidationResult<Readonly<Record<string, readonly string[]>>> {
  const source = defaultBundledCatalogProvider.getSourceCatalog()
  for (const [fullKey, parameters] of Object.entries(contracts)) {
    const sourceDefinition = messageAt(source, fullKey)
    if (!sourceDefinition) return { ok: false, error: `${fullKey}: parameter contract key is not platform owned` }
    if (!sameParameters(parameters, sourceDefinition.params)) return { ok: false, error: `${fullKey}: parameter contract differs from platform source` }
  }
  return { ok: true, value: contracts }
}

export const requiredSourceKeys = sourceManifest.requiredSourceKeys

export function validateRequiredSourceKeys(keys: readonly string[]): { ok: true } | { ok: false; missing: string[] } {
  const missing = keys.filter(key => !messageAt(defaultBundledCatalogProvider.getSourceCatalog(), key))
  return missing.length ? { ok: false, missing } : { ok: true }
}

const requiredSourceValidation = validateRequiredSourceKeys(requiredSourceKeys)
if (!requiredSourceValidation.ok) throw new Error(`Bundled English catalog is missing required source keys: ${requiredSourceValidation.missing.join(', ')}`)
