from pathlib import Path
import json,sys,traceback,urllib.parse
from chromium_helpers import Browser
R=Path(__file__).resolve().parent;BASE='http://127.0.0.1:4198';b=Browser();checks=[];input_records=[]
b.raw('Page.addScriptToEvaluateOnNewDocument',{'source':"window.__nativeInputs=[];for(const type of ['keydown','pointerdown'])addEventListener(type,e=>window.__nativeInputs.push({type:e.type,trusted:e.isTrusted,key:e.key||null}),true)"})
def check(n,v):checks.append({'name':n,'pass':bool(v)});print(('PASS ' if v else 'FAIL ')+n,flush=True)
def click_expr(expr):
 b.ev(expr+'.scrollIntoView({block:"center"})');pos=b.ev('(()=>{const r='+expr+'.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');b.call('input.performActions',{'actions':[{'type':'pointer','id':'mouse','parameters':{'pointerType':'mouse'},'actions':[{'type':'pointerMove','x':pos['x'],'y':pos['y'],'origin':'viewport'},{'type':'pointerDown','button':0},{'type':'pointerUp','button':0}]}]})
def button(name):
 expr='Array.from(document.querySelectorAll("button")).find(x=>(x.getAttribute("aria-label")||x.textContent).trim()==='+json.dumps(name)+')';b.wait('Boolean('+expr+')');click_expr(expr)
def input_text(value):
 expr='document.querySelector("input[type=search][aria-label=\\"Search render summaries\\"]")';click_expr(expr);b.call('input.performActions',{'actions':[{'type':'key','id':'keyboard','actions':[{'type':'keyDown','value':'\ue009'},{'type':'keyDown','value':'a'},{'type':'keyUp','value':'a'},{'type':'keyUp','value':'\ue009'}]}]});b.raw('Input.dispatchKeyEvent',{'type':'keyDown','key':'Backspace','code':'Backspace','windowsVirtualKeyCode':8});b.raw('Input.dispatchKeyEvent',{'type':'keyUp','key':'Backspace','code':'Backspace','windowsVirtualKeyCode':8})
 for c in value:b.key(c)
def count():return b.ev('document.querySelectorAll("button[aria-label^=\\"Inspect render \\"]").length')
def nav(q=''):
 input_records.extend(b.ev('window.__nativeInputs||[]'))
 b.nav('/operations/renders'+('?' +q if q else ''));b.locale('en');b.wait('document.body.textContent.includes("Render")')
try:
 b.raw('Emulation.setDeviceMetricsOverride',{'width':1440,'height':1000,'deviceScaleFactor':1,'mobile':False});nav();b.wait('document.body.textContent.toLowerCase().includes("unavailable")');check('ordinary-unconfigured-no-list',count()==0);b.shot('ordinary-unavailable')
 nav('rendersFixture=1');b.wait('document.querySelectorAll("button[aria-label^=\\"Inspect render \\"]").length===3');check('simulation-disclosed','SIMULATED' in b.ev("document.body.innerText"));check('exact-project-displayed','simulated-render-project' in b.ev("document.body.innerText"));check('not-global-inventory','not a global' in b.ev("document.body.innerText"));b.shot('desktop-list')
 input_text('Cinema');check('profile-search',count()==1);b.key('\ue004');b.key('\ue004');b.key('\ue004');check('native-tab-reaches-inspect',b.ev('document.activeElement.getAttribute("aria-label")')=='Inspect render render-zeta');b.key('\ue007');b.wait('document.querySelector("[role=dialog]")!==null');check('opaque-profile','Cinema <literal>' in b.ev('document.querySelector("[role=dialog]").textContent'));check('five-fields',b.ev('document.querySelectorAll("[role=dialog] .ff-property-row").length')==5);check('no-html-injection',b.ev('document.querySelector("[role=dialog] script")===null'));b.shot('desktop-details');b.key('\ue004');check('tab-inside-dialog',b.ev('!!document.activeElement.closest("[role=dialog]")'));b.key('\ue00c');check('escape-restores-launcher',b.ev('document.activeElement.getAttribute("aria-label")')=='Inspect render render-zeta')
 input_text('no-match');check('no-match-state','No matching render summaries' in b.ev("document.body.innerText"));button('Reset filters');check('reset-list',count()==3)
 click_expr('document.querySelector(".ff-render-controls label select")');b.key('\ue015');b.key('\ue007');check('native-status-filter',count()<3);input_text('no-match');button('Reset filters')
 click_expr('document.querySelector(".ff-render-controls label:last-child select")');b.key('\ue015');b.key('\ue007');check('native-id-desc',b.ev('document.querySelector("button[aria-label^=\\"Inspect render \\"]").getAttribute("aria-label")')=='Inspect render render-zeta')
 # Controlled simulated adapter only. UI actions below remain native pointer/keyboard.
 install='''(()=>{const el=document.querySelector('button[aria-label^="Inspect render "]');let f=el[Object.keys(el).find(x=>x.startsWith('__reactFiber$'))];while(f){const s=f.memoizedProps?.source;if(s?.adapter?.listProject){const h={source:s,original:s.adapter.listProject,held:true,pending:[]};s.adapter.listProject=(req,signal)=>h.held?new Promise(resolve=>h.pending.push({req,resolve})):h.original(req,signal);h.finish=()=>h.original(h.pending[0].req,new AbortController().signal).then(h.pending[0].resolve);window.__rendersHarness=h;return true}f=f.return}return false})()''';check('explicit-fixture-control-installed',b.ev(install))
 button('Refresh render summaries');b.wait('window.__rendersHarness.pending.length===1');check('loading-retires-content',count()==0);check('focus-stable-during-loading',b.ev('document.activeElement.textContent.includes("Cancel loading")'));button('Cancel loading');check('cancel-stable-focus',b.ev('document.activeElement.textContent.includes("Retry loading")'));b.ev('window.__rendersHarness.finish()');check('late-cancelled-success-ignored',count()==0);b.ev('window.__rendersHarness.held=false');button('Retry loading');b.wait('document.querySelectorAll("button[aria-label^=\\"Inspect render \\"]").length===3');check('retry-recovers',count()==3)
 for state in ['denied','unknown','unsupported','unavailable','error']:
  nav('rendersFixture=1&rendersFixtureFailure='+state);b.wait('document.body.textContent.toLowerCase().includes('+json.dumps(state)+')');check('query-'+state+'-no-content',count()==0)
 nav('rendersFixture=1&rendersFixtureEmpty=1');b.wait('document.body.textContent.includes("No render summaries in this snapshot")');check('loaded-empty-not-filter-empty',count()==0 and 'No matching render summaries' not in b.ev("document.body.innerText"))
 nav('rendersFixture=1&rendersFixtureLimited=1');b.wait('document.querySelectorAll("button[aria-label^=\\"Inspect render \\"]").length===1');check('limited-disclosed','limited' in b.ev("document.body.innerText").lower())
 b.raw('Emulation.setDeviceMetricsOverride',{'width':390,'height':844,'deviceScaleFactor':1,'mobile':True});b.locale('zh-CN');b.shot('narrow-chinese-list');check('narrow-no-page-overflow',b.ev('document.documentElement.scrollWidth<=window.innerWidth+1'));expr='document.querySelector("button[aria-label*=\\"render-zeta\\"]")';click_expr(expr);b.wait('document.querySelector("[role=dialog]")!==null');check('chinese-literal-preserved','Cinema <literal>' in b.ev('document.querySelector("[role=dialog]").textContent'));b.shot('narrow-chinese-details');b.key('\ue00c');check('narrow-escape-closes',b.ev('document.querySelector("[role=dialog]")===null'))
except Exception as e:
 (R/'HARNESS_ERROR.txt').write_text(traceback.format_exc());checks.append({'name':'harness-exception','pass':False,'error':str(e)})
finally:
 input_records.extend(b.ev('window.__nativeInputs||[]'));(R/'NATIVE_INPUT_TRUST.json').write_text(json.dumps(input_records,indent=2));check('trusted-native-input-events',bool(input_records) and all(x['trusted'] for x in input_records))
 network=[x for x in b.network if x['url'].startswith(('http:','https:'))];external=[x for x in network if urllib.parse.urlsplit(x['url']).hostname!='127.0.0.1'];queries=[x for x in network if '/api/' in x['url'] and x['method']=='GET'];(R/'HTTP_ASSERTIONS.json').write_text(json.dumps({'external_attempts':external,'render_or_other_api_queries':queries,'real_integration':False},indent=2));check('no-external-or-api-queries',not external and not queries)
 (R/'NATIVE_CHECKS.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2));failed=[x for x in checks if not x['pass']];rc=int(bool(failed));(R/'SMOKE_EXIT.json').write_text(json.dumps({'tree':json.loads((R/'TREE_BINDING.json').read_text())['FINAL_EXACT_IMPLEMENTATION_TREE'],'checks':len(checks),'passed':len(checks)-len(failed),'failed':failed,'assertion_exit':rc,'assistance':['CDP focus emulation','DOM locale and scrollIntoView','explicit simulated adapter React fiber control'],'physical_device':False,'screen_reader_speech':False},ensure_ascii=False,indent=2));b.raw('Browser.close',{});b.ws.close()
sys.exit(rc)
